### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#100]
co powiesz na promocję twoich filtrów w necie?

**Comment by azet12** [comment]
Im większy zasięg tym lepiej :). Mógłbyś bardziej rozwinąć myśl?

**Comment by xxcriticxx** [comment]
na fb juz widzialem

**Comment by MajkiIT** [comment]
wypozycjonujemy twoje filtry.

**Comment by azet12** [comment]
Byłbym wdzięczny :)

**Comment by MajkiIT** [comment]
Dodałem twoją listę do strony gdzie subskrybuje się moje filtry, czyli ktoś dodając subskrypcję moich dostaje też twoje.

**Comment by azet12** [comment]
dzięki wielkie! Jednak funkcja którą zastosowałeś w tym linku niestety nie działa w ublocku.

**Comment by MajkiIT** [comment]
No niestety się zgadza... coś pomyślę.

**Comment by MajkiIT** [comment]
Post na FB wrzucony. Artykuł na stronie też.

**Comment by azet12** [comment]
Jeszcze raz dziękuję :)
