### ISSUE TITLE
fotka.com

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#124]
http://fotka.com/zaloguj/?back_url=%2Fklubgwiazd%2Fmt%3Fdays%3D30

Usługa polega na zapisaniu się do subskrypcji SMS MT oraz otrzymywaniu dostępu do Klubu Gwiazd co 30 dni.

Aby aktywować usługę, należy wysłać SMS, o unikalnej dla każdego użytkownika treści, podanej na stronie: http://www.fotka.com/klubgwiazd/mt?days=30 na numer 60968

Opłata za SMSa aktywacyjnego wynosi 9 zł netto (11,07 zł brutto)

Wiadomość potwierdzającą aktywację pakietu na Twoim koncie otrzymasz, co 30 dni, jej treść jest następująca:

"Twoje konto zostalo doladowane pakietem gwiazdy na kolejne 30 dni."

Aby zakończyć usługę, należy wysłać SMS o treści STOP FOTKA na numer 60968

Subskrypcja dostępna jest w sieciach GSM: T-MOBILE, Orange, Plus, Play.

**Comment by azet12** [comment]
według użytkowników jest godna zaufania.
https://www.mywot.com/en/scorecard/fotka.com
https://play.google.com/store/apps/details?id=pl.fotka.app
