### ISSUE TITLE
pogodynka.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#128]
http://pogodynka.pl/sms/opis/

Koszt aktywacji Usługi „Ostrzeżenia IMGW”, wysłania wiadomości na numer 7468 w sieci T-mobile, PLAY oraz ORANGE wynosi 4,00 zł netto/4,92 zł brutto zł.

**Comment by azet12** [comment]
według użytkowników strona jest godna zaufania
https://www.mywot.com/en/scorecard/pogodynka.pl
