### ISSUE TITLE
Masakryczna grupa

### ISSUE THREAD

**Issue by azet12** [azet12/KAD#135]
Od pewnego czasu siedę na najróżniejszych grupach fb,
zobaczcie co się tutaj dzieje w komentarzach
https://www.facebook.com/groups/1036315203099452/ (zamknięta)
https://www.facebook.com/groups/1006651442760211/ (podobna, ale o wiele mniej członków i spamu)
to jest jakiś dramat, jednak czego się dziwić - ta grupa to głównie dzieci.

Oczywiście większość jest blokowana przez KAD.

**Comment by xxcriticxx** [comment]
co to jest?

**Comment by azet12** [comment]
Wejdź w dowolny post i zobacz komentarze.

**Comment by xxcriticxx** [comment]
amatorstwo

**Comment by xxcriticxx** [comment]
z listy mozna napisac fajny program. kto cie wkurzy podajesz jedo tel do wszystkich stron :)

**Comment by azet12** [comment]
Aktualizacja: grupa została zdjęta, z czego jestem w sumie zadowolony.
Ale znalazłem kolejną perełkę. https://www.facebook.com/groups/1006651442760211/ - spam jest na mniejszą skalę, ale no jest.
