### ISSUE TITLE
priv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#140]
http://sms.priv.pl/platna/

     

	
Reklamacje dotyczące płatnej bramki prosimy kierować na adres wapster@wapster.pl
By móc wysyłać smsy z naszej bramki SMS wyślij smsa o treści SMS.BMP pod nr 7928 (9 zł + VAT) lub nr 7228 (2 zł + VAT).

**Comment by azet12** [comment]
wygląda na bezpieczną, ceny są pokazane
