### ISSUE TITLE
jak ty sprawdzasz co z czym polaczone?

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#15]
whois?

**Comment by azet12** [comment]
Najczęściej można znaleźć dużo ciekawych rzeczy w kodzie źródłowym :)

**Comment by xxcriticxx** [comment]
czyli sub domains?

**Comment by azet12** [comment]
w przypadku np. https://github.com/azet12/KAD/issues/13 badając element np. tego przycisku "doładuj" można zobaczyć darmowedoładowania24.pl, do tego różne skrypty z firecpa.com. Autorzy tych stron bardzo często idą na łatwiznę. Do tego iframe jest na porządku dziennym.

**Comment by xxcriticxx** [comment]
czyli to jest tak zrobione zeby zarabijac kase dla autora
