### ISSUE TITLE
plsms.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#150]
Serwis jest usługą opartą na subskrypcji SMS MT. Opłata za subskrypcję usługi
wynosi 1.23 PLN brutto za każdą wiadomość przychodzącą z numeru 60168.
Opłata jest dopisywana do rachunku telefonicznego subskrybenta serwisu.

**Comment by azet12** [comment]
tutaj są tylko regulaminy, zablokowanie nic nie da, znam tę stronę bo dostaję spam na swoją komórkę od nich
