### ISSUE TITLE
sms spam polska 

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#163]
![img_2852](https://cloud.githubusercontent.com/assets/15007183/16733376/56dd1ef2-474f-11e6-890a-6735d80b2a6e.PNG)
![img_2853](https://cloud.githubusercontent.com/assets/15007183/16733382/5a89fa48-474f-11e6-912e-e38b3d46fe47.PNG)

**Comment by azet12** [comment]
no nieciekawe, niestety nic z tym nie zrobię, można tylko ostrzec ludzi na jakichś grupach lub forach
