### ISSUE TITLE
niezalezna.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#166]
to nowosc??

http://niezalezna.pl/83260-euro-2016-sukces-krychowiaka-i-polskiej-kadry

"Chcesz zabrać głos w ważnej sprawie? Chcesz podzielić się z nami swoją opinią, swoim zdaniem? Wyślij darmowy SMS o treści GPC na 8068 (0 PLN). Wasz głos jest dla nas cenny. Regulamin na www.gpcodziennie.pl/SMS"

**Comment by azet12** [comment]
Nie wygląda zbyt groźnie
