### ISSUE TITLE
Pokemon GO

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#167]
http://polscygracze.pl/pokemon-go-polska-konkurs-pokemon-go-plus-pakiet-trenera/

**Comment by xxcriticxx** [comment]
http://d5h.pl/r/zNspokemongo
http://pokemonkonkurs.pl/pp/zNspokemongo
http://pokemonkonkurs.pl/

Serwis INFO jest usługą subskrypcyjną, dzięki której użytkownik otrzymuję wiadomości zawierające przypomnienie o zbliżających się na najbliższe dni imieninach. Dzięki czemu już nigdy nie zapomni by złożyć życzenia swoim bliskim.. Serwis dostępny jest na telefony komórkowe bądź inne urządzenia, posiadające kartę SIM w sieci Orange, Plus, T-Mobile i Play. Koszt usługi to 4,92 zł brutto za każdy SMS otrzymany w ramach subskrypcji. W ramach usługi użytkownik otrzymuje maksymalnie 3 SMS/tydzień oraz dodatkowy SMS po aktywacji subskrypcji. Łączny koszt usługi w okresie miesiąca to: 63,96 zł brutto. Pobranie wybranych elementów multimedialnych może ponadto wiązać się z opłatami za transfer danych, zgodnie z cennikami operatora. Usługa jest aktywowana na czas nieokreślony, do czasu rezygnacji przez użytkownika. Aby dokonać rezygnacji należy wysłać SMS o treści STOP INFO na numer 60435 (koszt: 0 zł). Kontakt, również w sprawie reklamacji: biuro@phonemobile.pl. Organizator będzie kontaktować się z Klientem na podany przez niego numer telefonu lub e-mail. Regulamin serwisu znajduje się tutaj

**Comment by xxcriticxx** [comment]
redirect pokemongo-konkurs.pl/

**Comment by xxcriticxx** [comment]
Pobierz najnowszą polską wersję Pokemon Go:
tnij.xyz/5jb

**Comment by xxcriticxx** [comment]
tnij.at/pakietpokemonow

**Comment by xxcriticxx** [comment]
UWAGA! Coś dla fanów nowej gry Pokemon GO!
Rozwiąż zagadkę i odbierz 
pakiet TRENERA POKEMONÓW: http://utn.pl
Ps. odp to pikaczu :D

**Comment by xxcriticxx** [comment]
**Złośliwy Pokémon GO grasuje w Sieci. Gracze instalują go na własne życzenie**

http://www.dobreprogramy.pl/Zlosliwy-Pokmon-GO-grasuje-w-Sieci.-Gracze-instaluja-go-na-wlasne-zyczenie,News,74664.html

**Comment by azet12** [comment]
już wcześniej widziałem i dodałem niektóre z nich, dzięki
