### ISSUE TITLE
nowe adresy

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#17]
Może coś ci się przyda. 

||24streamer.com^
||5m4.pl^
||airmax90.com.pl^
||akademiagreya.pl^
||akazoo.pl^
||alebony.pl^
||alelte.pl^
||allmovies.com.pl^
||allplayer.pl^
||askfm-like.com.pl^
||asklike.pl^
||badabee.com^
||betterworld.eu^
||bieberpolska2016.pl^
||bookstar.pl^
||boostphone.pl^
||cda-filmy.com.pl^
||cda-online.pl^
||checkiq.eu^
||chron-telefon.com^
||clashofclansapp.pl^
||cs-goskiny.pl^
||dajemy50.*^
||darmowe-doladowanie.pl^
||deletefriend.pl^
||diamondmakeup.pl^
||dieta-personalna.eu^
||dodajsteam.pl^
||doladowanie-na-twoj-tel.pl^
||doladowanie365.pl
||doladowanko.com^
||doladuj-komorke.*^
||doladujsteam.pl^
||downloaded.pl^
||downloadfile.eu^
||downloadfiles.pl^
||e-filmy24*.pl^
||edownload.com.pl^
||egofile.pl^
||emotikonfb.com^
||enagrody24.pl^
||ero-tv.pl^
||extratesty.pl^
||face-podgladacz-24h.pl^
||faceportal.pl^
||facetools.pl^
||fb-szpieg.*^
||fejs-*.pl^
||fejsp*.pl^
||fejsszpieg.eu^
||fejstime.pl^
||file-share365.com^
||filebay.org^
||file*folders.pl^
||filmasy.*^
||filmowabaza.pl^
||filmy-365.pl^
||filmy-i-serale.pl^
||filmy.a33.pl^
||filmynet.eu^
||followersinsta.pl^
||fotomonto.pl^
||freedoladowania.pl^
||freetvonline.com.pl^
||friendviewer.pl^
||galapolsat.xn.pl^
||gamer24.pl^
||gangzalbani.pl^
||gdziejestdziecko.*^
||goracenagrody.pl^
||goracezdobycze.pl^
||gosciefb.pl^
||graotron.tv^
||hd-vod.pl^
||hdfilms.pl^
||hdsportstream.pl^
||hdvod*.pl^
||hersneakers.pl^
||hostshare.pl^
||hotawards.pl^
||icloudnet.*^
||ilebedemiecdzieci.pl^
||ilemasziq.pl^
||info-fitness.com^
||instalike.pl^
||iqfree.pl^
||kiedy-umrzesz.pl^
||kinocda.pl^
||klucze-csgo.pl^
||konkurs6.com.pl^
||konkursiphone.eu^
||konkurskosmetyki.pl^
||konkursmedia.pl^
||konkurspsc.pl^
||ktocieusunal.pl^
||leadmore.pl^
||lecgdziechcesz.pl^
||likeask.eu^
||listakonkursow.pl^
||livedownloadnet.pl^
||livestream365.pl^
||lokalizator24h.pl^
||losujgre.pl^
||lovelybox.eu^
||lte.ienet.pl^
||ltekonkurs.pl^
||mecze-hd.pl/wp-content/*/kod-zwrotny-sms.png
||meczezadarmowhd.pl^
||megacloudz.net^
||megadowner.*^
||megamovie.pl^
||minegift.pl^
||mobilnelte.pl^
||momoxxio.com^
||motoawards.pl^
||movie*base.pl^
||moviecreator.pl^
||movieplaytube.com^
||mysocialnetwork.pl^
||n-mobile.net^
||napisany.pl^
||nasza-ofiara.zoni.pl^
||news.maxcorpmedia.com/imp/$popup
||obrazkovo.*^
||oculusvsvr.pl^
||odpowiadam.pl^
||oferta4you.com.pl^
||onlinecalyfilm.pl^
||otobony.pl^
||pakiety5gb.pl^
||pamietnikiwampirow.tv^
||panel.eforsa.pl/widget/$subdocument,stylesheet,script
||patrzetu.pl^
||photodate.club^
||pl.mysafesmartphone.com^
||pl.tappsms.com^
||pl.wizappz.com^
||playmovie.pl^
||playvod.tv^
||pobieranie.online^
||pobierz*123*.pl^
||pobierz.kekuko.*^
||pobierzebooka.pl^
||pobierzgo.pl^
||pobierzpliki.net^
||pobraniowo*.pl^
||podarunkowartvagd.pl^
||podpiszpetycje.pl^
||pointhost.pl^
||pokolorujfb.pl^
||pokolorujfejs.eu^
||polokalizuj.pl^
||premium.darmowemp3.co^
||premium.superserwisy.pl^
||pro-stream.pl^
||profilszpieg.pl^
||promocyjne50zl.pl^
||przyjacielfb.pl^
||rapidfile.pl^
||realybooks.com^
||rejestrowanko.pl^
||riotpointslol.pl^
||rocket-host.*^
||samsung6edge.pl^
||samsungs6win.pl
||sg7edge.pl^
||sharehosting.pl^
||skinykonkurs.pl^
||slodkieklamstewka.*^
||smartawards.pl^
||sms4all.pl^
||speedfile.info^
||steamgry.eu^
||stebox.pl^
||stream18plus.pl^
||streamer-hd.pl^
||streamoo.pl^
||streams.net.pl^
||strefasexlive.pl^
||subkiller.pl^
||superciuchy.com.pl^
||szpieg-sms.pl^
||szpiegfriend.pl^
||szpiegofon.pl^
||szpiegsms.na.footoo.pl^
||szpieguj*.*^
||tapet0wo.pl^
||techawards.pl^
||techkonkurs.pl^
||telewizja-internetowa24.pl^
||timerfejs.pl^
||tracksms.pl^
||transmisje24.net^
||tv-internetowa.pl^
||tvplayer24.pl^
||twojanagroda.pl
||twojartykul.pl^
||twojdziennik.eu^
||twojeartykuly.pl^
||twojsamsung.pl^
||video-base.pl^
||videobay.*^
||vod24.*^
||watchonline24.pl^
||webgazeta.pl^
||wgrajka.pl^
||wikingowie.tv^
||winbike.pl^
||wincandy.pl^
||winlokalizator.pl
||winshoes.pl^
||wotgold.pl^
||wpisztu.pl^
||wspanialestulecie.tv^
||www.nowedoladowanie.pl^
||wybierz-nagrode.pl^
||wygraj-iphone6s.pl^
||wygrajfallout4.pl^
||wygrajgtavpc.pl^
||wygrajjustcause3.pl^
||wygrajnfs.pl^
||wygrajoverwatch.pl^
||wygrajpakiet.pl^
||wygrajpapierosa.pl^
||wygrajpsc.eu^
||wygrajsamsunga.com.pl^
||wygrajskiny.pl^
||wygrajxboxone.eu^
||wygrajz5.pl^
||wygrywajpakiety.pl^
||xawards.pl^
||xbox-konkurs.pl^
||y-tube.com.pl^
||zapisany.pl^
||zasilfona.pl^
||zegarfb.pl^
||zegarsmierci.com.pl^
||zgarnij-samsun.ga^
||zgarnijbilety.pl^
||zgarnijfona.pl^
||zgarnijkonsole.pl^
||zlokalizowano.pl^
||zmienkolor-fb.pl^
||telefotki.pl^
||z0x.pl^
||firesub.pl^
||doladuj-fona.pl^

**Comment by xxcriticxx** [comment]
mamy azet12 z glowy na tydzien :)
