### ISSUE TITLE
Nowa strona do zablokowania - z ankietami do wygrania niby Samsung

### ISSUE THREAD

**Issue by AnnaBells** [azet12/KAD#170]
h**XX**p://pl30.mircrosoft.com-odebrac-nagrode.pw/d1-v639-pl-l/index.html?isp=Orange%20Polska%20Spolka%20Akcyjna&model=Desktop&voluumdata=BASE64dmlkLi4wMDAwMDAwNC1iYmZkLTRkZDQtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLmY0ZWUwMDAwLTRlNGYtMTFlNi04YWVlLTY1Y2ZiOWQ3ZThmMl9fY2FpZC4uY2M5MGYyMDctNjEyMy00NTkyLTg2OWMtZmEzNzFhM2M1Y2UwX19ydC4uREpfX2xpZC4uNjg2ODZjZjItNmIxMS00NTAzLTg4NTctYmJhZDg1YTcwOWMzX19vaWQxLi4zMzJiMzEzZC1mZjRhLTRkMjctOWI2Zi1hYzUyYTZhNjA0MDRfX3ZhcjEuLjU2Mjk2OGUxZmZhNmZkMGEwZDZjYmM0OF9fdmFyMi4ubi9hX192YXIzLi53aWZpX192YXI0Li53aW5kb3dzX192YXI1Li5QTF9fcmQuLl9fYWlkLi5fX2FiLi5fX3NpZC4u&sourceid=562968e1ffa6fd0a0d6cbc48&match=n/a&carrier=wifi&mob_pf=windows&country=PL&cpc=0.0039

h**XX**p://ukozz.bigprizezone.0764.pics/?sov=2977947451&hid=dtfpfdldjhddvnl&&redid=6201&gsid=22&campaign_id=20&id=XNSX.-r6201-t22

 czasem  ankieta z firefox / czasem o Microsoft.

**Comment by azet12** [comment]
dzięki za zgłoszenie
