### ISSUE TITLE
Generator Doladowan

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#178]
http://great-files.org/cjokGbxTWs
http://great-files.org/NbeLSwFxhj
http://great-files.org/pkLNgfStCF

**Comment by azet12** [comment]
dzięki, przy okazji kolejne offersy
`http://m.pl.lifehackz.net/app/mobile/pl_mlh46/pinlanding?page=0&landing_url=http%253A%252F%252Fm.pl.lifehackz.net%252F%253Fad_id%253Dpl.mlh.W2M.PL_Lifehacks_Service.PL_Lifehacks_Service_Backlink_ALL_ALL.98926%2526f%253Dpl_mlh46%2526ea%253Doffersubscribe%2526tagid%253D98926%2526retargeting%253D1%2526s%253Dpl_mlh46&ad_id=pl.mlh.W2M.PL_Lifehacks_Service.PL_Lifehacks_Service_Backlink_ALL_ALL.98926&tagid=98926`

`http://m.pl.p0rnking.com/app/mobile/pl_mpk44/pinlanding?page=0&landing_url=http%253A%252F%252Fm.pl.p0rnking.com%252F%253Faff%253Anetwork%253Daascpa%2526aff%253Apath_new%253DSP5rW%2526ad_id%253Dpl.mpk.W2E.PL_PORNKING.PL_PORNKING_CPA.98251%2526f%253Dpl_mpk44%2526aff%253Atid_new%253D10290ffe50bdc036d2949a938e5728%2526page_version%253D13%2526tagid%253D98251%2526ea%253Doffersubscribe%2526retargeting%253D1%2526aff%253Aoffer_renew%253D21572%2526s%253Dpl_mpk44%2526aff%253Aaff_sub4%253DSPXH-102b7d7cb7b7e80e3ab25d51c7f90c%2526aff%253Aaff_sub3%253D%2526aff%253Aaff_sub2%253D%2526aff%253Apath_renew%253DSP5rU%2526aff%253Aaff_id%253D780%2526aff%253Aoffer_new%253D21570%2526aff%253Aaff_sub%253D&page_version=13&ad_id=pl.mpk.W2E.PL_PORNKING.PL_PORNKING_CPA.98251&tagid=98251`

`http://play.quiz-fun.com.my/lpx/swhVF5igug?aff=ck-verd&reqid=1034619020&oid=2792&s1=191611|&affid=452&s2=`

oraz przekierowujące
`7112132.com
 mobile-redirection.com
 exit-o.com
 mobstarr.com
w2mobile.com`


co za śmietnik..
