### ISSUE TITLE
powtarzające się reguły

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#18]
`napisany.pl has been made redundant by napisany.pl`
`onlinecalyfilm.pl has been made redundant by onlinecalyfilm.pl`
`fb-szpieg.com.pl has been made redundant by fb-szpieg.com`
`fb-podgladacze*.blogspot.com has been made redundant by fb-podglad*.blogspot.com`

**Comment by azet12** [comment]
Z tym fb-szpieg to jakiś błąd raczej jest, bo sprawdziłem (lokalnie) i fb-szpieg.com nie blokuje w żaden sposób fb-szpieg.com.pl - te strony w żaden sposób nie są połączone ze sobą.
