### ISSUE TITLE
co za śmietnik..

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#181]
http://softwar.io/pl/developers/576167614-fun-cool-free-llc
http://ollando.com/?lang=pl-PL
http://www.funskan.pl/
http://mtupk.pl/
http://wirtualnysms.pl/
http://quizotest.pl/
http://playmobia.com/poland/
http://fb-znajomi.pl/
http://goracynews24.prv.pl/home/index.html

**Comment by azet12** [comment]
co to za strony? - http://mtupk.pl/ ; http://playmobia.com/poland/ ; http://ollando.com/?lang=pl-PL
znalazłeś na nich offery?

`fb-znajomi.pl ; quizotest.pl ; goracynews24.prv.pl` - niebezpieczne

wirtualnysms.pl jest bezpieczny, funskan.pl duplikat, softwar.io bezpieczne

**Comment by xxcriticxx** [comment]
nie dalem tobie do analizy

**Comment by xxcriticxx** [comment]
http://playmobia.com/poland/   <---- Koszt otrzymania jednej wiadomości Premium z numeru 60502/60503/60523/60524 SMS/MMS MT to 5 zł; 6,15 zł z VAT

**Comment by azet12** [comment]
już patrzę, jak na razie mam to
http://m.pl.ollando.com/index.cfm?CFID=bef1d769-7745-4c21-b4e3-9d053d145969&CFTOKEN=0&GO=LOGINRANDD&m=&cpID=

**Comment by xxcriticxx** [comment]
ollando.com

Usługa jest odpłatna. Cena Usługi płatna przez Usługobiorcę wynosi 6,15 zł brutto za
każdą otrzymaną przez Usługobiorcę wiadomość. Usługa obejmuje otrzymywanie 3
wiadomości tygodniowo, które będą wysyłane planowo we wtorek, czwartek i sobotę o
godzinie 16:00. Dodatkowo po rejestracji w Usłudze Usługobiorca otrzyma jedną płatną
wiadomość w cenie 6,15 PLN brutto.

**Comment by azet12** [comment]
na mtupk.pl znalazłem tylko regulaminy - `mtupk.pl/JzN
mtupk.pl/OW3
mtupk.pl/xpp
mtupk.pl/RJA
mtupk.pl/yc8
mtupk.pl/HZt
mtupk.pl/oRd
mtupk.pl/c3w
mtupk.pl/eWT
mtupk.pl/FN1`

ale jest połączone z ilovemobi.com (operuje nim chyba mobiltek) który już jest w kad

--
playmobia.com - znalazłem jakieś przestarzały syf, ale i tak dodam do filta `http://m.pl.playmobia.com/index.cfm?CFID=9365d18e-6bbb-411e-84c7-577c9a2d4b2d&CFTOKEN=0&GO=ERROR&m=&cpID=&status=invalidLogin`
