### ISSUE TITLE
smietnik continues 

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#182]
http://sd.unix.id.lv/?nLaIVrqOUImC1QcduNKheaEzHA31nVy_PLUS__PLUS_ohGYfptG28_EQUALS_
http://rt.fotoxpert.ro/?kcd8qBrQiG3SBQqI_PLUS_iOPT6_SLASH_dbHaDHRrRVaEsbRr9xMw_EQUALS_
http://agroadamek.pl/pobierz_generator_doladowan_plus.html

**Comment by azet12** [comment]
dwa pierwsze linki nie są raczej polskie, do tego przekierowują do jakiegoś malware czy cholera wie czego, zgłoszę to do spam404

agroadamek.pl przekierowuje do innych wyłudzaczy, głównie `islandmob.com`
`http://agroadamek.pl/heroes_5_dzikie_hordy_rar.html`
