### ISSUE TITLE
kino-tv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#185]
Niniejszy landing page jest częścią usługi Wygrywa.pl, która umożliwia zdobycie określonej ilości punktów oraz odblokowanie przydzielonych jej nagród szczegółowo określonych w zakładce "Nagrody" na stronie panelu użytkownika w/w usługi. Niniejszy landing page jest usługą Premium SMS dostępną w sieciach Plus, T-Mobile, Orange oraz Play. Koszt wysłania SMS wynosi 25,00zł (30,75zł brutto). Użytkownik wysyłając SMS pod podany na stronie numer oświadcza, że akceptuje Regulamin naszej usługi dostępny pod tym adresem. Życzymy przyjemnego korzystania ze strony i wielu zdobytych nagród!

**Comment by azet12** [comment]
eforsa
