### ISSUE TITLE
Batman vs Superman: Świt sprawiedliwości (2016) CDA PL !

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#186]
http://adf.ly/1aiSYG 

http://www.grebu.net/?do=ydl&yt_vid=QQS_EF4-ZNQ

http://batman-v-superman-film-online.prv.pl/

http://batman-v-superman-lektor.5v.pl/

**Comment by azet12** [comment]
pierwszy zgłoszę do spam404, drugi to nie mam pojęcia co to, ale niebezpieczne nie jest

--dodatkowo `twojefilmy-online.pl`
