### ISSUE TITLE
prv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#188]
http://online-tarzan-legenda-lektor-pl.prv.pl/
http://tarzan-legenda-ogladaj-2016-pl.prv.pl/
http://tarzan-legenda-caly-filmpl.rfv.pl/
http://tarzan-legenda-cda-pl.rfv.pl/
http://legion-samobojcow-online.rfv.pl 
http://gdzie-jest-dory-online.rfv.pl
http://183-metry-strachu-online.rfv.pl
http://nice-guys-rowni-goscie--online.rfv.pl
http://agent-i--pol-online.rfv.pl
http://gwiezdne-wojny-przebudzenie-mocy-cda.rfv.pl
http://co-ty-wiesz-o-swoim-dziadku-cda.rfv.pl
http://sasiedzi-2-online.rfv.pl
http://zjawa-online.rfv.pl
http://obecnosc-2-cda-pl.rfv.pl/
http://iluzja-2-online-pl.rfv.pl/
http://d8x.pl/r/yTFniewinne-2016-pl
http://www.legionsamobojcow.kinowepremiery.pl/
daa.pl/tarzan-legenda-pl
daa.pl/przyjazn-czy-kochanie-2016
daa.pl/wojownicze-zolwie-ninja-wyjscie-z-cienia-pl
http://movie.g.info.pl/Iluzja%202
http://down.g.info.pl/Iluzja%202.avi/699
http://movie.g.info.pl/Wojownicze%20żółwie%20ninja:%20Wyjście%20z%20cieni a
http://down.g.info.pl/Wojownicze%20żółwie%20ninja:%20Wyjście%20z%20cieni a.avi/699
http://down.g.info.pl/Tarzan:%20Legenda.avi/699
http://movie.g.info.pl/Tarzan:%20Legenda
http://movie.g.info.pl/Przyjaźń%20czy%20kochanie?
http://down.g.info.pl/Przyjaźń%20czy%20kochanie?.avi/699
fullplayer.pl/ogladaj/przyjazn-czy-kochanie-pl
pobierzgo.pl/pobierz/przyjazn-czy-kochanieplsub480pbdripxvid-tvm4inavi

**Comment by azet12** [comment]
zablokuję całą domenę rfv.pl - to jest jedno wielkie wysipisko i widać, że administratorzy mają gdzieś ich stronę

reszta zablokowana, dodatkowo strony na prv.pl zgłosiłem do administracji w celu usunięcia

**Comment by azet12** [comment]
zgłoszenie prv.pl https://github.com/azet12/KAD/issues/196
