### ISSUE TITLE
<>< 

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#189]
hyba dead ale mozna dodac http://full-movies-online.cba.pl/?cat=2

http://giftcode.pl/

**Comment by azet12** [comment]
strony nie są martwe
 pierwsza strona: 

`full-movies-online.cba.pl`
nakładka survey `||www.adworkmedia.com/gTemplate.php`
inne przekierowujące `wap.mobiltek.pl` ; `swshlds.com`

druga ma w nazwie strony gift code, ale sprzedaje konta, znając życie te konta szybko wygaszają, dodam do podejrzanych. Dzięki
