### ISSUE TITLE
,

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#191]
http://kiwicheat.com/poker-polska-hd-hack-cheats-free-purchases/

**Comment by xxcriticxx** [comment]
ten jest hyba nie polski http://pokemongo-hack.top/

**Comment by xxcriticxx** [comment]
to jest legalne czy nie? https://www.qpony.pl/

**Comment by xxcriticxx** [comment]
check it out http://www.house.pl/pl/pl//news/zlap-je-wszystkie

**Comment by xxcriticxx** [comment]
more poki http://pokecoinsy.wirtualnie.pl/

**Comment by azet12** [comment]
wszystkie angielskie zgłosiłem do Spam404 i ESET

`www.qpony.pl/` bezpieczne i tak, legalne
`www.house.pl` bezpieczne

ostatnie - oryginalna strona `wygrajpokecoins.pl` - dodałem do listy i zgłosiłem do ESET
