### ISSUE TITLE
mxrevsharepp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#193]
MXRevshare - zarabiaj codziennie $0,5 za klikanie , bez inwestycji.
Po 10 dniach masz $5, ktore zarabiaja na Ciebie

**Comment by azet12** [comment]
nie wiem co o tym myśleć :/

**Comment by xxcriticxx** [comment]
obojętny, niezrzeszony, niezdecydowany, neutralny? zrob jakis nowy tag i zamknij
