### ISSUE TITLE
KADRep

### ISSUE THREAD

**Issue by azet12** [azet12/KAD#200]
Najróżniejsze strony phishing będą teraz zgłaszane przeze mnie do firm i organizacji takich jak Netcraft, ESET, Symantec, Bitdefender, Avira oraz ostatecznie do **administratora hostingu w celu kompletnego zablokowania niebezpiecznej zawartości strony**.

Lista zablokowanych stron jest dostępna tutaj: https://github.com/azet12/KAD/blob/KADRep/lista.txt
**Uwaga:** To nie jest filtr! Jest to tylko lista informacyjna, nie usprawni w żaden sposób blokowania.
Powyzszy link pokazuje tylko usunięte strony w aktualnym miesiącu.

Listy archiwalne są dostępne tutaj: https://github.com/azet12/KAD/tree/KADRep/Archiwum-2016

W statystykach Netcraft widnieję pod nickiem "Azet12" - http://toolbar.netcraft.com/stats/reporters

**Comment by xxcriticxx** [comment]
Lista 404: Not Found

**Comment by azet12** [comment]
Jeszcze nie stworzyłem na aktualny miesiąc, bo ostatnio dość mało tych stron powstaje.

**Comment by xxcriticxx** [comment]
czekam bo niemam co czytac
