### ISSUE TITLE
hdsportstreams.pl

### ISSUE THREAD

**Issue by F4z** [azet12/KAD#201]
Link - `http://hdsportstreams.pl/`
Najpierw musisz kliknąć w odtwarzacz, a potem zobaczysz, to co na obrazku poniżej.

![image](https://cloud.githubusercontent.com/assets/11742596/17645296/aabadae8-61a1-11e6-8afa-68c7c6f839ee.png)

Swoją drogą po przejrzeniu regulaminu - `http://klubgraczy.pl/regulamin.pdf` widzę, że na stronie numer 5 i 6 są podane kolejne ciekawe strony. Niektóre blokowane są przez "KAD", ale część nie.

![image](https://cloud.githubusercontent.com/assets/11742596/17645310/5132fdd8-61a2-11e6-9249-4738ebe36fdb.png)

Tutaj lista stron, które nie są blokowane:
<pre>
movieplaytubes.pl
hdvod48.pl
hdsportstreams.pl
streams18plus.pl
streamershd.pl
24streamers.pl
foldersfiles.pl
filesfolders.pl
yourhost.pl
megadowner.pl
yourarticle.pl
weebgazeta.pl
booksstar.pl
realyybooks.pl
</pre>

**Comment by azet12** [comment]
Cześć, dzięki za zgłoszenie.
Zgadza się, czasami w regulaminach pojawiają się strony, jednak zwykle jest to czubek góry lodowej.
