### ISSUE TITLE
cos dla spam 404

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#202]
https://docs.google.com/document/d/1ZV3qiHGmibORhMqMnf672kbzmUPWFHQ5iURt1buBOEw/edit?pref=2&pli=1
http://us1.springfiles.net/?d=hY6xU3HvqlRz2rlNc5rrYVvv92swsLUqYqKyPXeXlzZsv4w4TPLTeRD63H0G%2BoEPT6iTCECN21EUs5QBDcotUUqIdighnGAeKIBSFjraK6F4yzu%2FYS4ou2AqL7tjKg2xPH5K4BF1W8QQcV%2FsA3dfgVQ%2BAZ9QDBvJBEtK3B9aY4lcaizF51Ymw6QYb8vuSw63%2FR5v9qZ3aPqhcWn%2FrHpZ4LJuDrLbJwapwnZX%2Fe4qUYvBKQaCkhNJ3tNWTM%2FVBu2a0Amn2%2BAD%2FJmvEK%2FF6EmhNftLrT%2FwrLt%2FpOX%2BZIXhxTHkrp0j16ScftemgCeIq4MO2qmHF9%2FCjEqViYlJmZClVsaZ8VMy0%2BUKMoP8Dj2N5XM4ju10MOz7O3e2qSF%2Fur46eu7fdRTyxXlTtbIyTu3TWQy4xl5W15sNB9efXlvdMxcH3zISdZJoSCfAbkZznSG3KN5o

**Comment by azet12** [comment]
doc zgłosiłem do Google, a springfiles do Spam404 i ESET
