### ISSUE TITLE
xmc.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#204]
nie groznie wyglonda moze znajdziesz cos wiecej

http://www.irak.xmc.pl/
http://www.portugalia.xmc.pl/
http://www.grecja.xmc.pl/
http://www.usa.xmc.pl/tag/kongres/
http://www.japan.xmc.pl/
http://www.lasery.xmc.pl/
http://www.norwegia.xmc.pl/
http://www.jezykwloski.xmc.pl/

**Comment by azet12** [comment]
wygląda na bardzo stare, nic ciekawe nie znalazłem
