### ISSUE TITLE
forum.mintshost.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#205]
http://forum.mintshost.pl/topic/757-kochaj-2016-film-onlinepobierz/
http://forum.mintshost.pl/topic/758-b%C3%B3g-w-krakowie-2016-film-onlinepobierz/
http://forum.mintshost.pl/topic/759-warcraft-pocz%C4%85tek-2016-film-lektor-pl-online/

**Comment by azet12** [comment]
często pojawiają się takie zabiegi na różnych forach, KAD blokuje wszystko dokąd przekierowują te wątki
