### ISSUE TITLE
boo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#213]
boo.pl jest serwisem hostingowym oferującym najwyższą jakość za najniższą cenę.
Płacisz SMSem lub płatnościami elektronicznymi oraz przelewem. Rejestrujesz wybrane
konto mail i www, aby później uiszczać stałą opłatę - zależną w czasie i wartości od rodzaju
wykupionego konta. Zawsze możesz dokupić przestrzeń dyskową czy usługi lub powiększyć
swoje konto. Opłaty te są jednorazowe i nie wpływają na wysokość opłacanego abonamentu.

**Comment by azet12** [comment]
zwykły hosting, nic niebezpiecznego
