### ISSUE TITLE
host file

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#225]
@azet12 zrobil by host file tak jak na 404

**Comment by azet12** [comment]
myślałem nad tym, tylko niestety różne filtry takie jak te z gwiazdką (np. costam*.pl) nie będą działać i więcej roboty z tym by było

**Comment by xxcriticxx** [comment]
ja juz zaczalem http://pastebin.com/KZD1dsn4

**Comment by xxcriticxx** [comment]
@azet12 bendzie cos z tego?

**Comment by azet12** [comment]
aktualnie nic takiego nie planuję, poza tym tak szczerze to nie mam za bardzo czasu
