### ISSUE TITLE
tracksms.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#25]
30.75 pln

**Comment by azet12** [comment]
tylko że strona pokazuje, ile usługa kosztuje. Nie wiem czy to fejk

połączone z http://trackgsm.pl/ http://trackgsm.co.uk/ http://trackgsm.de/

**Comment by xxcriticxx** [comment]
platny service?

**Comment by azet12** [comment]
regulamin mówi o jakichś punktach sms i internet, dodam do podejrzanych
