### ISSUE TITLE
microsoft.com-wybrane-szczesliwym-zwyciezca.top

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#260]
Strona wyłudzająca dane/oszustwo typu Wygrałeś Ajfona 

Pełny działający adres URL:

`d8.pl.microsoft.com-wybrane-szczesliwym-zwyciezca.top/d1-v739-pl-l/index.html?isp=Orange Polska Spolka Akcyjna&model=Desktop&voluumdata=BASE64dmlkLi4wMDAwMDAwMC04ZWFjLTRjYTMtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLjI4ZWVkMDAwLWFhOTQtMTFlNi04YmVmLTczOTBmNThhMjQwMV9fY2FpZC4uOGIxN2VjYzItZGFmNC00MWI4LThlM2UtYzdiZTZiMjJmZGZhX19ydC4uRF9fbGlkLi45YzdiOWRjMi04MjhlLTRjMGMtODJmOS1mYmUyODBiZGI3ZjBfX29pZDEuLmQxNmU5NmQxLTA0ZDAtNGQwNy04ODkxLTQxMjQ0OThkM2I5M19fdmFyMS4uMTU0Mjk2M19fdmFyMy4uN19fdmFyNC4uUExfX3ZhcjUuLjc4NF9fdmFyNi4uMjEyNzMxMjEzMl9fcmQuLmhlcmFjZ2pjdXFta1wuXGNvbV9fYWlkLi5fX2FiLi5fX3NpZC4u&websiteid=1542963&keyword=&categoryid=7&country=PL&IMPRESSIONID=2127312132&bid=0.00116`

**Comment by xxcriticxx** [comment]
@FadeMind masz zamontowane filtry KAD?

**Comment by FadeMind** [comment]
Filtry KAD blokują. Przepraszam za zamieszanie. Pozdrawiam. Dobry projekt.

**Comment by xxcriticxx** [comment]
@FadeMind wpadaj od czasu do czasu jak sie nudzisz

**Comment by FadeMind** [comment]
@xxcriticxx  dziękuję za zaproszenie.

@azet12 możesz przygotować plik hosts dla projektu: 

https://github.com/FadeMind/hosts.extras

??

**Comment by azet12** [comment]
Myślałem nad plikiem hosts, jednak aktualnie jestem rzadko przy komputerze, więc nie mogę za bardzo.

Dodatkowo, taki plik byłby trochę słabszy od filtra do ublocka, chyba z wiadomych przyczyn, więc nie wiem czy jest sens.

**Comment by xxcriticxx** [comment]
@FadeMind prosze bardzo

https://github.com/xxcriticxx/.pl-host-file/blame/master/hosts.txt
