### ISSUE TITLE
KAD ala host 

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#265]
brzmi jak nowa kanapka z McDonald's

http://pastebin.com/2q2YthBA

**Comment by xxcriticxx** [comment]
@FadeMind happy testing!

**Comment by azet12** [comment]
wszystkie reguły z gwiazdką *, slashami /x/, kreskami pionowymi || i inne filtry oczywiscie nie beda dzialac w pliku hosts, wiec takie cos jest mniej bezpieczne. Dodatkowo, niektóre strony mogą być przepuszczane przez to, bo jeśli jest reguła 0.0.0.0 x.pl to już nie zablokuje strony y.x.pl.

**Comment by xxcriticxx** [comment]
@azet12 @FadeMind sobie poprawi i potestuje

**Comment by azet12** [comment]
Proszę bardzo: https://github.com/azet12/KADhosts/blob/master/KADhosts.txt
@xxcriticxx @FadeMind

**Comment by xxcriticxx** [comment]
:)

**Comment by xxcriticxx** [comment]
@azet12 fade moze jeszcze by chcial ver 127.0.0.1

**Comment by FadeMind** [comment]
@azet12 Dziękuję. Dodam odpowiednie reguły do folderu 📦 https://github.com/FadeMind/hosts.extras
i zrobię pull dla projektu głównego 📦 https://github.com/StevenBlack/hosts

Rozumiem, że plik https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt będzie aktualizowany na bieżąco?

**Comment by azet12** [comment]
Tak, w miarę możliwości. Filtr do ublocka jest u mnie nadrzędny

**Comment by FadeMind** [comment]
@azet12 FYI https://github.com/StevenBlack/hosts/pull/203
