### ISSUE TITLE
sms-za-darmo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#27]
Zapisując się do usługi BRAMKA SMS otrzymujesz na start za darmo 500pkt do wykorzystania. Bramka SMS pozwoli wysłać 50 SMS ZA DARMO (10pkt za sms). Serwis OK jest usługą subskrypcyjną w której bramka będzie automatycznie doładowywana punktami za każdy dzień subskrypcji. Serwis dostępny jest we wszystkich sieciach: Orange, Plus, T-Mobile i Play. Koszty subskrypcji SMS wynoszą 2,46zł brutto, za każdy otrzymany przez użytkownika SMS. Otrzymasz max. 1 SMS dziennie (do czasu rezygnacji z usługi BRAMKA SMS, której można dokonać wysyłając SMS o treści STOP OK na numer 60228). Do usługi subskrypcyjnej OK zapisujesz się za darmo i dostajesz 500pkt za darmo do wykorzystania w bramce SMS. Darmowe smsy możesz wysyłać do wszystkich sieci: Plus, Play, Orange i T-Mobile. SMSy testowe na numer, który aktywował usługę OK, możesz wysyłać za darmo i bez limitu (bez zużycia pkt). Warunki korzystania z serwisu określa Regulamin. Podmiotem realizującym usługę o podwyższonej opłacie jest Play The Game Ltd. z siedzibą Office M5, Tigne Place, Tigne Street, Sliema, Malta, zarejestrowana w rejestrze przedsiębiorców prowadzonym przez MFSA pod numerem C 57080. Reklamacje i pytania dotyczące działania Serwisu i promocji można składać PTG w formie pisemnej na adres korespondencyjny Skrytka Pocztowa 6892, ul. Chłodna 51, 00-867 Warszawa lub elektroniczny na adres e-mail: info@ptgame.eu, lub telefonicznie pod numerem (22) 830 00 37 lub 22 331 93 38, w dni robocze, w godz. 9:00-17:00.

**Comment by azet12** [comment]
dzięki ptgame.eu znalazłem kolejne perełki
www.wapster.pl

www.superpyton.pl
www.dragondefense.pl
www.zlotyskok.pl
www.roslinkivsduchy.pl
www.grajwciemno.pl
www.drpacman.pl
www.super-barman.pl
www.data-smierci-na-telefon.pl
www.prezentofon.pl
www.magicznarybka.pl
www.wojnaczolgow.pl
www.mobisciaga.pl
www.footballmanager.com.pl

**Comment by xxcriticxx** [comment]
wapster znana firma w tej branzy
