### ISSUE TITLE
pozyczki

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#270]
http://hksfa.org/include/pd/pkd-pozyczki-chwilowki.php
http://litukredyt.cf/chwilwki/chwilwki-rybnik-rynek-15-wypeni-wniosek-i-dosta-pienidze.html
http://kredytskysiv.cf/poyczka-dla/najlepsza-poyczka-dla-rencistw-czarnkw.html
http://pagikredytpl.gq/sms/informacje-o-szybkich-kredytach-przez.html
http://azstabkredytpl.ga/pozyczka/pozyczka-polska-sp-z-oo-forum.html
http://ininkredytpl.gq/poyczka/poyczka-na-remont-mieszkania.html
http://suvekredyt.gq/opinie/poyczka-polska-forum-opinie.html
http://kredyttijer.ga/bez-bik/poyczka-bez-bik-krakow-milaki-1.html
http://ulala-olivia.interiowo.pl/30ZL.html
http://razsiezyjee.xlx.pl/a_26_b.php
http://hipoteczna-6f.c0.pl/18-06-2016-id7hh.php

**Comment by azet12** [comment]
większość nie działa, jedynie podejrzana jest `http://hksfa.org/include/pd/pkd-pozyczki-chwilowki.php`
bo prosi o bardzo dokładne dane a nawet nie ma certyfikatu ssl..
