### ISSUE TITLE
tytułfilmu-online.pl/cda

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#283]
Schemat domeny jest następujący:

**tytułfilmu**-online.pl
na przykład

hxxp://pitbullniebezpiecznekobiety-online.pl/cda/

**Comment by azet12** [comment]
reguła `*-online.pl` moze takie strony blokowac, lecz nie wiem czy nie bedzie za duzo false positive

**Comment by FadeMind** [comment]
@azet12 będzie blokować np gry-online.pl, więc odpada (chyba, że pozna się inne sub domeny dla filmów z -online.pl na końcu adresu.

**Comment by FadeMind** [comment]
@azet12 Ewentualnie można dodać wyjątki z -online.pl 
```
@@gry-online,pl
```

**Comment by azet12** [comment]
ok, dodam

**Comment by F4z** [comment]
Kilka innych stron, które są blokowane:
`http://www.films-online.pl/index/`
`https://cda-online.pl/`
`http://www.texet-online.pl/`
`http://www.invicta-online.pl/`
`https://pasjans-online.pl/`

Może lepiej będzie skorzystać z wyrażeń regularnych i spróbować z taką regułą?
Będzie można część domen wykluczać.
`/:\/\/(?!cda|www\.films|films|.*\.gry|www\.invicta|www\.texet|pasjans).*-online\.pl/`
http://regexr.com/3eo76

Macie więcej podobnych linków?
Pytam, bo może ta reguła by wystarczyła?
`/-online\.pl\/cda\//`

**Comment by azet12** [comment]
@F4z dzięki wielkie, na chwilę obecną dodam `/:\/\/(?!cda|www\.films|films|.*\.gry|www\.invicta|www\.texet|pasjans).*-online\.pl/`
