### ISSUE TITLE
-online.pl 

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#287]
`www.f1-online.pl`
`www.films-online.pl`
`www.cda-online.pl`
`www.soccer-live.pl`

**Comment by F4z** [comment]
Na przykład:
`/:\/\/(?!www\.cda|cda|www\.f1|f1|www\.films|films|.*\.gry|www\.invicta|www\.texet|pasjans).*-online\.pl/`

**Comment by xxcriticxx** [comment]
soccer-live pomylka sorry

! Last modified: 24 Nov 2016 ! Version: 2016112401 

![capture1](https://cloud.githubusercontent.com/assets/15007183/20629918/0adf0ee8-b2fc-11e6-99ca-1e60ea5b9a3e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15007183/20629919/0c775418-b2fc-11e6-9634-71705fbc1e36.PNG)

**Comment by F4z** [comment]
@azet12  przez tę regułę strony `https://saturn.pl/` oraz `https://mediamarkt.pl/` nieprawidłowo się wyświetlają.

![image](https://cloud.githubusercontent.com/assets/11742596/20635232/ba7be6d8-b35a-11e6-9233-1e3945f40f28.png)

Poprawiona reguła:
`/:\/\/(?!www\.cda|cda|www\.f1|f1|www\.films|films|.*\.gry|www\.invicta|www\.texet|pasjans|stat-..\.ms).*-online\.pl/`

**Comment by azet12** [comment]
ok, zaktualizałem

**Comment by F4z** [comment]
@azet12 ta reguła nadal nie jest dobra.
Trzy kolejne przypadki, które są blokowane:
`https://www.google.pl/#q=-online.pl`
`https://namegrep.com/#-online.pl`
`https://www.shodan.io/search?query=-online.pl`

Poprawiona wersja:
`/:\/\/(?!cda|www\.films|films|.*\.gry|www\.invicta|www\.texet|pasjans)[a-z0-9]{1,}-online\.pl/`
Tylko znowu może być tak, że będzie za dużo blokować.

**Comment by xxcriticxx** [comment]
`laskonline.pl`

**Comment by azet12** [comment]
może sobie darujmy tę regułę? te strony z filmami i tak tylko przekierowują

**Comment by F4z** [comment]
Tak chyba będzie najlepiej.
