### ISSUE TITLE
troche shitu

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#293]
http://zarabiajnaokazjach.pl/
http://bhpfirelex.pl/lib/dobre-pozyczki-skarbiec.php
http://artykulytechniczne.pl/biuro/pomocna-pozyczka-gdansk-saperow/
http://piotrduda.pl/sass/pozyczki-skarbiec-forum.htm
http://konkurs.kss.org.pl/extra/pozyczki-pod-zastaw-gdynia.html
http://top-casinos-sites.com/
http://193.104.50.251/ankiety/Gdy-dzieci-halasuja-na-klatce-schodowej-ank5079.html
http://szybkagotowka-8x.c0.pl/27-07-2016-id1933ee.php
http://vrewbgwefbds9wh5.blox.pl/2016/07/Kredyt-studencki-w-mbanku.html
http://onlinecredit-5s.cba.pl/30-06-2016-id767af.php

**Comment by xxcriticxx** [comment]
http://kredytskysiv.cf/poyczka-dla/najlepsza-poyczka-dla-rencistw-czarnkw.html
http://litukredyt.cf/chwilwki/chwilwki-rybnik-rynek-15-wypeni-wniosek-i-dosta-pienidze.html

**Comment by azet12** [comment]
wszystkie te strony co zgłosiłeś (też w https://github.com/azet12/KAD/issues/291 i https://github.com/azet12/KAD/issues/292) to jakieś landing pejdże, śmieciowe racja, ale też neutralne
