### ISSUE TITLE
striprtg.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#32]
ten jest najlepszy **HALL OF FAME** 

Strip Rentgen w Twoim telefonie!

Montują go na lotniskach aby sprawdzić co masz na sobie a teraz Ty możesz go mieć w swoim telefonie!

Chcesz zabłysnąć w towarzystwie?! Zrobić zaskakujący żart?! Do pobrania za DARMO

Prześwietl swoich znajomych, zobacz co noszą pod ciuszkami. Być może coś ukrywaja? ;)

Dodaliśmy nowe super zdjęcia! Może Twoja koleżanka nosi nóż za podwiązką albo pistolet w stringach? A Twój kolega ma tatuaż na pośladku?

**Comment by azet12** [comment]
kolejne
striprtg.pl

www.magiczneruny.pl
www.operacjarzeka.pl
www.piekielnakuchnia.mobi
www.gradiamenty.pl
www.wykreslanka.com.pl
www.piardofon.pl
www.magicznytotem.pl
www.mojarybka.pl
www.trzepwleb.pl
www.bombkimikolaja.pl
iqmilionera.pl
wisielec.com
czarnypunktgra.pl
www.roslinkivsrobale.pl
