### ISSUE TITLE
pytanie

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#325]
Planujesz przerobić swoje filtry na pasujące do ad away ?

**Comment by mogin6** [comment]
Tak chciałbym mam dośc uporczywych reklam

**Comment by mogin6** [comment]
Tylko jak to zrobić ...

**Comment by xxcriticxx** [comment]
@MajkiIT niewiem czy oto wam chodzic https://github.com/azet12/KAD/issues/265

**Comment by MajkiIT** [comment]
@xxcriticxx tak, dzięki wielkie

**Comment by mogin6** [comment]
Wklepałem ale nie dziala

**Comment by azet12** [comment]
@mogin6 KAD blokuje jedynie strony z przekrętami.

**Comment by MajkiIT** [comment]
@azet12 ale jemu chodzi, że nie może nawet tego zaimportować.

**Comment by mogin6** [comment]
tak nie dziala

**Comment by xxcriticxx** [comment]
@mogin6 tutaj masz `http://mobione.pl/adaway.txt` albo te co ja zrobilem https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt

**Comment by mogin6** [comment]
Pisze pakiet online nie dostępny

**Comment by mogin6** [comment]
Sprawdzam

**Comment by azet12** [comment]
Nie korzystam z adaway i nie wiem za bardzo jak to działa. Ale jeśli wystarczy dać źródło pliku hosts to wystarczy dać to: `https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt`
jeśli nie działa to nie wiem.

**Comment by xxcriticxx** [comment]
@mogin6 musisz uzywac ver `RAW` jest pod `https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt`

**Comment by mogin6** [comment]
Online niedostępny nie działa

**Comment by mogin6** [comment]
Ten działa http://mobione.pl/adaway.txt

**Comment by xxcriticxx** [comment]
ja uzywam tego do programu pi-hole podobne do adaway

**Comment by xxcriticxx** [comment]
@mogin6 przerub sobie kada liste i moja tak aby wyglondala tak samo jak ta co dziala

**Comment by mogin6** [comment]
Zielony jestem nie wiem jak to się przerabia pokombinuję dzięki jak coś.

**Comment by xxcriticxx** [comment]
@mogin6 versia KAD w RAW dziala?

**Comment by mogin6** [comment]
https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt - nie działa
https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt - nie działa
http://mobione.pl/adaway.txt- działa

**Comment by xxcriticxx** [comment]
@mogin6 przetestuj `http://pastebin.com/raw/wm05J4DY`

**Comment by mogin6** [comment]
Nie działa

**Comment by xxcriticxx** [comment]
ok a jakie blendy masz? more info?

**Comment by mogin6** [comment]
Lokalny: niedostępny(e),Online: niedostępny(e)  --- jeżeli filtr nie działa jest tak
Lokalny:19 gru 2016,    Online: 19 gru 2016     --- jeżeli działa to tak

**Comment by xxcriticxx** [comment]
ok moment zrobimy mnieszy pliki moze jakis limit jest

**Comment by xxcriticxx** [comment]
@mogin6 http://pastebin.com/raw/v0WBGdAK

lista ma 5 stron tylko zobacz co sie dzieje jak wejdziesz na strone

**Comment by mogin6** [comment]
Nie otwierają się te strony

**Comment by xxcriticxx** [comment]
zadnych blendow? czyli dziala z adaway?

**Comment by mogin6** [comment]
No jest że niby nie działa w tych ustawieniach Lokalny: niedostępny(e),Online: niedostępny(e)  ale strony się nie wyświetlają więc chyba działa...

**Comment by mogin6** [comment]
parodia ten ad away

**Comment by xxcriticxx** [comment]
@mogin6 na jaki system ty to potrzebujesz? czemu adaway?

**Comment by mogin6** [comment]
Jeżeli jest coś lepszego na androida to np co ? adblock?

**Comment by mogin6** [comment]
android

**Comment by xxcriticxx** [comment]
na telefon czy na tv box?

**Comment by mogin6** [comment]
smartfon tak

**Comment by xxcriticxx** [comment]
@mogin6 `https://adguard.com/en/adguard-android/overview.html`

**Comment by mogin6** [comment]
Miałem go tylko że on musi działać w tle a ja mam słaby smartfon 1gb ramu i mi cięło jak otworzyłem np: faceboka dlatego chciałem coś żeby dodało filtry i nie mieliło się w tle

**Comment by xxcriticxx** [comment]
@mogin6 pora hyba bendzie na nowy telefone

`http://forum.xda-developers.com/showthread.php?t=1916098`
`http://androidforums.com/threads/guide-best-ad-blocking-no-app-needed-for-rooted-phone.853586/`

>>> Compatibility?
ANDROID FAMILY: 4.x, 5.1.x, 6.x, 7.x (5.0.x not supported, android memory leaks)
DEVICE FAMILY: Anything which has 1 GB of RAM and atleast 1.2GHz CPU minimum.

This MOD requires some amount of RAM (4MB - 8MB) and CPU for effective functionality. "Anything below the compatibility specs" might be working But wll be Slow and Laggy. PLEASE DO NOT PM me or POST on this thread for issues if so. I Don't and Won't Support.

WiFi/Mobile: Please disable PROXY to use this 'MOD' else no blocking will happen.

**Comment by mogin6** [comment]
No chyba tak Sprawdzę ten wątek dzieki.

**Comment by xxcriticxx** [comment]
@mogin6 sorry man

**Comment by xxcriticxx** [comment]
@azet12 zamkniesz please
