### ISSUE TITLE
[NSFW] abdcn.pro 

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#327]
see https://github.com/MajkiIT/polish-ads-filter/issues/1775

**Comment by FadeMind** [comment]
Dodatkowo
```
pl2.titan-man.pro
```
ale można dać też
```
*.titan-man.pro
```

**Comment by FadeMind** [comment]
Blog jest scamem w czystej postaci. Większość obiektów na stronie to statyczne zdjęcia i boxy. Forum Facebooka jest mylące. Dodatkowo link `Report` odsyła do `hxxp://ac-feedback.com/report_form/`

```
ac-feedback.com
```
która z automatu jest blokowana przez ESET Smart Security:
