### ISSUE TITLE
adware popup scam 

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#330]
```
filiser.tv
ekino-tv.pl
kinostar.tv
filmy.to
iitv.pl
```

- popups
- scam
- stream z openload vshare etc z dodatkowymi reklamami

Reference: https://github.com/MajkiIT/polish-ads-filter/issues/1781

**Comment by xxcriticxx** [comment]
z easylist forum 

 `||130.211.230.53^$popup`

**Comment by MajkiIT** [comment]
@azet12 dodałem te reguły już.

**Comment by MajkiIT** [comment]
@FadeMind @FadeMind @azet12 
btw zmienił się ipek na `130.211.212.60` jak coś w PL filtrach oblatuje to regex
