### ISSUE TITLE
pinka.pl

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#336]
Linkowanie do stron podszywających się pod cda dot pl
`http://pinka.pl/pin/280162/Nowy-poczatek-Caly-Film-Lektor-PL-Po-Polsku-Online-CDA-ZALUKAJ`

`Nowy początek Online TU` linkuje do `http://cda-player.pl/f/Nowy%20pocz%C4%85tek+PL`, który jest już na Twojej liście zablokowane @azet12 .

**Comment by azet12** [comment]
Widziałem już, niestety administracja serwisu Pinka ma to chyba w nosie :/
