### ISSUE TITLE
gratuluje

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#347]
https://github.com/StevenBlack/hosts

**Comment by FadeMind** [comment]
@MajkiIT See: https://github.com/StevenBlack/hosts/commit/45a2574c70e3b7eda7c0d55ea06cccd1ceace93f

https://github.com/StevenBlack/hosts/commit/74cb2b4a0f6080ed37a1b1efda7093ea10e741a6#diff-dc344840c13bd62d09145d802e0644f4

**Comment by MajkiIT** [comment]
@FadeMind wiem wiem, że mam zapłon, ale ja nie wiedziałem :(

**Comment by xxcriticxx** [comment]
@FadeMind tam nadgodziny tam wyrabia

**Comment by MajkiIT** [comment]
@xxcriticxx Dzięki

**Comment by FadeMind** [comment]
![s](http://i2.kym-cdn.com/photos/images/newsfeed/000/345/169/bc7.png)
