### ISSUE TITLE
download statistics

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#350]
@azet12 ile downloadow miales w grudniu?

**Comment by azet12** [comment]
To w ogóle można sprawdzać? Gdzie niby?

**Comment by xxcriticxx** [comment]
zagadaj z @MajkiIT on ci na pewno pokaze

**Comment by MajkiIT** [comment]
Ja bazuje na logach z moje VPS czyli przekierowania z https://certyficate.it/adblock/adblock.txt na github. Github pokazuje tylko tylko ruch na stronie projektu a nie ilość pobrań, bo wynika to z użycia serwerów cachujących na froncie.

**Comment by azet12** [comment]
Taki bajer. Dzięki za informację
