### ISSUE TITLE
tzxse.pl

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#370]
https://forum.dobreprogramy.pl/t/uwaga-co-to-jest-http-tzxse-pl/521428
Swoją drogą strona jest blokowana przez uBlock Origin Extra

**Comment by azet12** [comment]
przekierowuje do strony która już jest na liście
`http://zapisujemy24.pl/s/Prywatne-zdjecia-z-portalu-Facebookcom-do-dnia-02022017-Kraj-Polska-Ilosc-zdjec-62617723-ABY-POBRAc-ZDJeCIA-WPISZ-NUMER-TELEFONU`
