### ISSUE TITLE
może cię zainteresuje

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#382]
https://zaufanatrzeciastrona.pl/post/uwaga-na-rzadowa-witryne-infekujaca-odwiedzajacych-ja-uzytkownikow-ransomware/

**Comment by azet12** [comment]
Tragedia. Strona powinna zostać wyłączona na czas sprawdzania bezpieczeństwa. Ale jak widać oni wiedzą lepiej.
Nie skupiam się nad linkami z malware, bo to tego potrzeba dużo pracy i osób.
ESET blokuje `urpl.gov.pl` jako phishing, już zgłosiłem fałszywy alarm.
