### ISSUE TITLE
s.arclk.net

### ISSUE THREAD

**Issue by adreporter** [azet12/KAD#385]
https://s.arclk.net/tr?id=01cc84903dd2a9e78571671307af24473764960cc3.nr&tk=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWIiOiI1MjU2OTM0MjNmOTBjNmM5ODBiZmZkZDciLCJ0cyI6IjAyMjcxOTEyIiwiZCI6IndlYnNlYXJjaGluc2lkZXIuY29tIn0.6uZvSGnDDnWJefrXEGY1GCyN79thwdt8GuknJFtsEAk

**Comment by azet12** [comment]
Przekierowuje mnie do chyba jakiejś wygaśniętej domeny. Coś innego widzisz?
