### ISSUE TITLE
system-control.win

### ISSUE THREAD

**Issue by adreporter** [azet12/KAD#404]
http://system-control.win/pl/10/?city=Krakow&isp=UPC+Polska

Na Chrome mam coś takiego:
<img width="960" alt="bez tytulu" src="https://cloud.githubusercontent.com/assets/18214146/24657714/a7c0abac-1947-11e7-88a9-8dfcf8123cb0.png">
<img width="960" alt="bez tytulu2" src="https://cloud.githubusercontent.com/assets/18214146/24657722/acf0d930-1947-11e7-810b-cd0133995013.png">
Nie można z tego wyjść i gdziekolwiek klikniesz to wyją syreny.

**Comment by azet12** [comment]
Strona już nie działa.

**Comment by adreporter** [comment]
Jakiej przeglądarki używasz? Bo na Firefoxie rzeczywiście nie działa ale na Chrome nadal działa.

**Comment by azet12** [comment]
Testuję strony na różnych przeglądarkach, zwykle Chrome lub Firefox; strona nie działa na żadnej. Sprawdź, czy strona nadal się wyświetla jak odświeżysz stronę.

**Comment by adreporter** [comment]
Masz rację, po usunięciu ciasteczek i odświeżeniu, strona nie działa.
