### ISSUE TITLE
driveridentifier.com

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#417]
SCAM RISKWARE

**Comment by azet12** [comment]
Niewiele znalazłem o tej stronie,
tylko jakiś wątek na reddicie: https://www.reddit.com/r/computertechs/comments/2g8hd0/driveridentifiercom/
tutaj mówią, że jest ok.

Virustotal wskazuje tylko 3/61 https://www.virustotal.com/pl/file/1eb69b1452ba0587a199c3bf8ed5f2df13a44ffe84b87510777cbbf47ec0a448/analysis/
