### ISSUE TITLE
[NSFW] thebestgoodgame.com

### ISSUE THREAD

**Issue by adreporter** [azet12/KAD#431]
http://thebestgoodgame.com/ball8t/?bemobdata=eyJjaWQiOiJlYmUxMGQ3ZS1kNDA2LTQ1YmUtYTExYy0wMDc4ODRkZWJmM2EiLCJsaWQiOiJkNWM3OGY3NS1mZTI2LTQ1MzAtOGQ4MS0wOTQyMmMyMTRlZTIiLCJmaWQiOiJmMGYxNGVhZi03MGRkLTRhNWEtOTlhZC1lZmY2MDU0M2U0NWMiLCJyIjpudWxsLCJvaWQiOlsiNGE0ZTE0NTktNDZlOS00ZDMyLThiNTQtM2EzMGVmZWFjN2JkIl0sInJpZCI6MCwicGlkIjowLCJjdTEiOiI3MDQ2NDUiLCJjdTMiOiIyNTAiLCJjIjowLjAwMDE0fQ%3D%3D

**Comment by azet12** [comment]
Jakiś śmiecowy reflink, nie jest wart dodawania do listy.
