### ISSUE TITLE
Lista w formie pliku hosts

### ISSUE THREAD

**Issue by p0358** [azet12/KAD#433]
Tak, żeby można było korzystać z listy blokując hosty bezpośrednio na routerze, np.
```
127.0.0.1 domena.tld
```
```
0.0.0.0 domena.tld
```
Byłbym wdzięczny, gdyby lista była również udostępniana w takiej formie :)

**Comment by xxcriticxx** [comment]
https://github.com/azet12/KADhosts

**Comment by p0358** [comment]
O, nie zauważyłem na stronie, a nie sprawdzałem innych repo, dzięki :)

**Comment by xxcriticxx** [comment]
you welcome
