### ISSUE TITLE
combinationprizes.party

### ISSUE THREAD

**Issue by adreporter** [azet12/KAD#434]
http://combinationprizes.party/?isp=UPC%20Polska%20Sp.%20z%20o.o.&voluumdata=BASE64dmlkLi4wMDAwMDAwMy1kMzA5LTRiOWUtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLjRiMzlhODAwLTRlNDEtMTFlNy04Njc0LTA2NzljYjAxMDVkOF9fY2FpZC4uZmQ4NDNiZTctMDZhYy00OWQ1LTg5NzUtMmRmMzMyODE2MTUzX19ydC4uREpfX2xpZC4uZTVjZDg3ZTItNWNhZC00M2U2LThkYmEtY2YzMzIzYjg3N2E4X19vaWQxLi45OGE4NDlkOS1iODMyLTRlMmUtOGVkNS0zODU3ODZiNDJjYTFfX3ZhcjEuLmJlNjQzMWNlLTNlMjEtNGY1OC1iY2ViLTQ4MTNmMWZiYTgxOV9fdmFyMi4uMTUyMDBfX3JkLi5obXZ6elwuXGV4Y2x1c2l2ZXJld2FyZHNcLlxraWZiXC5cZ2RuX19haWQuLl9fYWIuLl9fc2lkLi5fX2NyaS4uX19wdWIuLl9fZGlkLi5fX2RpdC4uX19waWQuLl9faXQuLl9fdnQuLjE0OTcxNDMxMjk2MDI&clickid=be6431ce-3e21-4f58-bceb-4813f1fba819&zoneid=15200#b

**Comment by azet12** [comment]
Wygląda na to, że już nie działa.
