### ISSUE TITLE
adwcleaner.pl

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#437]
SCAM. Jakiś `#januszbiznesu` stworzył stronę i chce kasę na serwer by ludzie mogli pobierać adwcleaner :D 

Oficjalne strony: 
https://www.malwarebytes.com/adwcleaner/
https://toolslib.net/downloads/viewdownload/1-adwcleaner/

Najlepsze jest to, że google wysoko pozycjonuje adwcleaner dot pl w wynikach :D 

![image-20170624-001](https://user-images.githubusercontent.com/9846948/27508745-3da9c07a-58ec-11e7-97a4-7c34baf214f3.png)

@azet12 zalecam blokadę ;) Pozdrawiam

**Comment by azet12** [comment]
Eh, ci nasi przedsiębiorcy... Przynajmniej nie ma adware w instalatorze.
Zgłosiłem to do Malwarebytes. Zobaczymy, co mają do powiedzenia.

**Comment by azet12** [comment]
Odpowiedzieli, że przekazali to do sekcji prawnej i tam zobaczą, czy strona jest legalna i w razie czego ją zablokują... prawie 2 tygodnie temu. Strona nadal działa.
