### ISSUE TITLE
klubgraczy.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#44]

**Comment by azet12** [comment]
wiele stron z przekrętami należy do klubgraczy jednak ona sama w sobie raczej nie jest niebezpieczna, to wygląda bardziej jak jakaś przykrywka. Planuję wkrótce dodać coś w stylu `/klubgraczy/` do filtrów, ale nie wiem, czy nie będą wtedy zbyt nachalne.
