### ISSUE TITLE
caly-film-online.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#445]
https://caly-film-online.pl/lektor-pl-napisy-bez-limitu-War-for-the-Planet-of-the-Apes.html

![screenshot from 2017-07-18 06-58-31](https://user-images.githubusercontent.com/15007183/28313921-9813ae8e-6b86-11e7-94ac-d284d8f2877c.png)

**Comment by azet12** [comment]
Dodam jutro, aktualnie nie mam dostępu do komputera.
