### ISSUE TITLE
ankieta od chrome

### ISSUE THREAD

**Issue by blocker999** [azet12/KAD#459]
Fajna ankieta mi dziś wyskoczyła, proszę to zablokować.
![ankieta](https://user-images.githubusercontent.com/23176832/29773257-d19b3faa-8bfc-11e7-84a8-9f3387a7e50e.png)

http://competition1904.cdn-network4-server5.biz/default.aspx?u=bl3pte4&o=xbkkvzb&m=1&t=main2_desk&f=1

**Comment by azet12** [comment]
Już jest offline.
