### ISSUE TITLE
filmu.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#462]
http://filmu.pl/jackie-lektor-pl

![capture](https://user-images.githubusercontent.com/15007183/30004698-22dc7114-90a2-11e7-8935-a229c500d8ef.PNG)

**Comment by MajkiIT** [comment]
@xxcriticxx już to jest 
https://github.com/azet12/KAD/blob/59457edfeaee0e2dc554a69e36aa7cc38b7c5e71/KAD.txt#L811
