### ISSUE TITLE
imperialwinners.men

### ISSUE THREAD

**Issue by adreporter** [azet12/KAD#486]
http://imperialwinners.men/?brand=Desktop&model=Desktop&browser=Chrome&voluumdata=BASE64dmlkLi4wMDAwMDAwNS01NGEwLTRhOGYtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLjBjNjIxODAwLTk3Y2ItMTFlNy04MGRlLTY3ZTQ1NjU2M2QzY19fY2FpZC4uYWNiMGY3NTctNTdjNy00MmY0LWExNjItMTMzODM0NzFjYWFhX19ydC4uREpfX2xpZC4uMWY5ZmExODYtYmNhMS00YmIzLTgxYWItZjQxOWVkZDY2YjgxX19vaWQxLi45OGE4NDlkOS1iODMyLTRlMmUtOGVkNS0zODU3ODZiNDJjYTFfX3ZhcjEuLmtQTDI1NlQwMDEzMzFHMTAwNVEyMTJOUFUwM00yQVdGMFRQQzFNUmIxOFdWMUMwUTAzTTJBMDBfX3ZhcjIuLjEyMDkwNi1SajB1dEo0aXNFdWlOWVdpYWduNl9fcmQuLm1hY2FuZGVsbFwuXGNvbV9fYWlkLi5fX2FiLi5fX3NpZC4uX19jcmkuLl9fcHViLi5fX2RpZC4uX19kaXQuLl9fcGlkLi5fX3BlaWQuLl9faXQuLl9fdnQuLjE1MDUyMzE3NTIyODc&pubid=120906-Rj0utJ4isEuiNYWiagn6&kimia=kPL256T001331G1005Q212NPU03M2AWF0TPC1MRb18WV1C0Q03M2A00#

**Comment by gomoku** [comment]
test z drugiego komputera
