### ISSUE TITLE
"You can't comment at this time"

### ISSUE THREAD

**Issue by gomoku** [azet12/KAD#490]
Nie mogę komentować na tym repo czyiś wątków (nie tylko @MajkiIT https://github.com/azet12/KAD/issues/485 ale też np. @adreporter  https://github.com/azet12/KAD/issues/486) , bo wyskakuje komunikat jak w tytule, czyli "Nie możesz komentować w tej chwili", 
~~natomiast swoje wątki komentować mogę~~, 
~~**_EDYTOWANE i DODANE 20:45_**: teraz to nawet nie mogę skomentować własnego wątku: https://github.com/azet12/PopupBlocker/issues/89 i odpisać dla @hawkeye116477~~ 
_**ZNOWU EDYTOWANE i DODANE 21:04:**_ wyłączyłem uBlocka i już mogę u siebie, cuda niewidy, więc niech będzie, że raz mogę, a innym razem nie mogę u siebie, natomiast dalej nie mogę u innych, próbowałem następujących kroków:
- czyszczenie ciasteczek
- wylogowanie/zalogowanie na github
- wyłączenie uBlocka Origin oraz Greasemonkey
- odpalenie na pustym profilu bez żadnych aktywnych dodatków
- testowanie na różnych przeglądarkach Opera 47 64bit / Firefox 55.0.3 32 bit / Firefox Nightly 56.0b9 64bit z wyłączonymi wszystkimi dodatkami, na prawie świeżych profilach.

Kilka dni temu miałem to samo przez chwilę, ale wyłączenie uBlocka pomogło, a teraz nic nie pomaga.
Ktoś też tak ma/miał? Cholery idzie już dostać z tym githubem, tyle razy już podobne błędy wyskakiwały.

![](https://s3.dodajfote.pl/2017/09/13/githubac277.png)

**Comment by azet12** [comment]
Nigdy nie miałem takiego problemu. Niestety nie mogę ci pomóc. Może napisz do supportu GitHuba?

**Comment by azet12** [comment]
A co do tych leków - pewnie istnieją, jednak ogólnie strona, która jest zgłaszana jest swojego typu landing page. Najczystsza reklama, "ranking" pewnie zakłamany - lepiej blokować.

**Comment by gomoku** [comment]
> @azet12:  Może napisz do supportu GitHuba?

Ok napisałem dzisiaj koło południa i czekam na odpowiedź.

**Comment by gomoku** [comment]
> Hi Gomoku,
> 
> The message you are receiving is not the result of any technical issue that we are aware of, but may be a result of configurations or settings performed by another user. We do consider these types of actions confidential, and will not be able to share any details beyond this.
> 
> Cheers,
> xxxx
> GitHub Support

Czyli nie wina po stronie GitHuba, no po mojej kurcze też nie, jeszcze jutro sprawdzę na innym komputerze, wiem tylko, że kiedyś też miałem taki sam komunikat na MajkiIT i też napisałem do supportu Githuba i też dostałem taką samą odpowiedź i okazało się, że mam banana na MajkiIT od MajkiIT.

**Comment by azet12** [comment]
Może MajkiIT cię zablokował i nie możesz pisać w jego tematach i repozytoriach? Nie wiem. Jak powiedziałem, nie jestem w stanie ci pomóc.

**Comment by gomoku** [comment]
Na to wygląda, natomiast zastanawia mnie ta anonimowość w komunikatach githuba, czyli to dlaczego nie jest napisane, że nie mogę czegoś zrobić bo ktoś mnie zablokował. Bo ta anonimowość powoduje efekt taki, że nie wiadomo czy to jakiś błąd po stronie githuba, czy ktoś mnie zablokował, co powoduje z kolei, że za każdym razem trzeba pisać do githuba i dopytywać się czy to nie błąd po ich stronie.
