### ISSUE TITLE
Strony wyłudzające pieniądze

### ISSUE THREAD

**Issue by adreporter** [azet12/KAD#496]
norton.pl
recenter.pl
elektro-studio24.pl
designer.ski
fh-falkon.pl
promo-max.pl

**Comment by azet12** [comment]
recenter.pl offline

designer.ski - na opineo są różne opinie, ale większość jest pozytywna. dodać i tak?

**Comment by adreporter** [comment]
Te pozytywne opinie i odpowiedzi ze sklepu są napisane przez tą samą osobę. O widzę, że już dodałeś, dzięki.

**Comment by adreporter** [comment]
@azet12 Dziękuję, że już dodałeś do listy stronę designer.ski
Może ten "sklep" był wiarygodny do czerwca, bo od lipca te pozytywne opinie były pisane prawie codziennie, najprawdopodobniej przez tą samą osobę. Poza tym na opineo w tych pozytywnych opiniach występują śmieszne ksywy jak np. czopek
Jeżeli chodzi o stronę recenter.pl jeszcze wczoraj działała, ale nie ważne: na opineo miałem bekę z negatywnych opinii, bo ta strona dosłownie wszystko "sprzedaje": komputery, telefony, agd, rtv, itd.
Nie wiem czemu ale mnie szczególnie rozśmieszył początek następującej opinii: "W sklepie złożyłem zamówienie 8 września na zmywarkę, a następnie przesłałem pieniądze na konto firmy. Do taj chwili nie ma towaru, firma nie odbiera telefonów oraz nie odpowiada na meile. Jestem zaniepokojony, chyba też sprawę zgłoszę na policji !!!"
Nie no zmywarkę zamówił :D Wiele osób "zamówiło" również pralkę, laptopa, jeden nawet "kupił" tam wiertarkę :D
