### ISSUE TITLE
idownload.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#50]
Serwis jest usługą subskrypcyjną dostępną w sieci Plus, T-Mobile, Orange, Play. Dla sieci PLUS poprzez wysłanie sms aktywacyjnego użytkownik potwierdza zaakceptowanie Regulaminu serwisu. Dla pozostałych sieci użytkownik akceptuje regulamin poprzez wpisanie na stronie kodu PIN otrzymanego darmowym sms'em na podany numer telefonu komórkowego. Wraz z aktywacją subskrypcji użytkownik otrzymuje wynik wykonanego testu. Subskrybenci serwisu otrzymują sms w wtorek, czwartek oraz sobotę około godziny 19:00. Sms zawiera horoskop na najbliższe dni. Koszt za każdy sms przychodzący to 4,92 zł z VAT. Dezaktywacji subskrypcji można dokonać w dowolnym momencie poprzez wysłanie SMS o treści STOP GAME pod numer 60474(Koszt wysłania sms to 0 zł). Regulamin serwisu znajduje się tutaj. W przypadku reklamacji prosimy wysłać email na adres: biuro.obslugi.klienta.game@gmail.com

**Comment by azet12** [comment]
offline

**Comment by azet12** [comment]
ale dodam do podejrzanych w razie czego
