### ISSUE TITLE
fade.org.br / game4144.cdn5-data95-server3.top

### ISSUE THREAD

**Issue by gomoku** [azet12/KAD#522]
1_ 
Wyszukiwałem w Google, i kliknąłem w ten link znaleziony przez Google:
http://fade.org.br/mvp/iglobe_39156.htm

2_
przekierowało mnie na 
http://game4144.cdn5-data95-server3.top/?utm_medium=NQ3aDvyuBCtafRQJPeFC66tm%2bMNW8T%2baflxP0d0AJGo%3d&t=main3

![](https://s3.dodajfote.pl/2017/11/08/kad1688e5f88c266ff74.jpg)

3_
Gdy chciałem to zreprodukować czyli kliknąłem ponownie pierwszy link to już nie przekierowało na drugi, wyczyściłem ciasteczka, i znowu kliknąłem i dalej nie przekierowało, tylko ładowała się strona z pierwszego linku:

![](https://s3.dodajfote.pl/2017/11/08/kad2291fea824c51ab0f.jpg)

4_ 
Gdy odświeżyłem/przeładowałem stronę z 2_ to przekierowało na kolejną:
http://appstoresmobiles.com/?url=ba5aKLn7NaGVbBDNSSX45QMFBezFMw8Yw76MLoTLgqe2o2KKhhyg%2bcUvZc7S5RVwATPCOd6%2bytp0KDQyqg8KP0mG2wtswggIWl8qVcZi4MMerBADAQL5D5HXBcoTQALBdUph%2fHMUYme0XZRWUCoJTUorfT%2fIO2E8LqkbUvx%2bMG8UQgBZtsKa7RCgc3mi7dIeiPK9%2b2Ovv1w%3d
ale nie wczytało się bo KAD przekręty to zablokował.

**Comment by azet12** [comment]
Wygląda na to, że te strony już nie działają.
