### ISSUE TITLE
Nowy atak na konta bankowe via DOTPAY fake

### ISSUE THREAD

**Issue by FadeMind** [azet12/KAD#552]
https://zaufanatrzeciastrona.pl/post/nowa-atak-na-konta-bankowe-czyli-czemu-wszyscy-oszukuja-na-dotpaya/
https://niebezpiecznik.pl/post/uwaga-na-sms-y-z-numeru-przypominam-rzekomo-od-dotpaya/
```
oplata351.pl
rozliczeniedp.pl
pay726372.info
```

**Comment by MajkiIT** [comment]
@FadeMind te 2 domeny są już dead
```
oplata351.pl
rozliczeniedp.pl
```
