### ISSUE TITLE
serial-botoks-za-darmo.pl

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#555]
http://serial-botoks-za-darmo.pl/

**Comment by azet12** [comment]
To chyba landing page do Showmaxa, więc jest bezpieczna.

**Comment by MajkiIT** [comment]
Nie za bardzo. Kliknij w cokolwiek i dostaniesz redirecta na to co sam blokujesz.

**Comment by azet12** [comment]
@MajkiIT Klikam i nic się nie dzieje (nawet z wyłączonym UB), za każdym razem przekierowuje mnie do Showmaxa.
