### ISSUE TITLE
Chamstwo, znęcanie i patologia na repozytorium POL listy filtrów + repozytorium KAD listy filtrow + repozytorium uBlock Origin + MozillaPL Forum - nagłośnienie sprawy. #2 [KONTYNUACJA]

### ISSUE THREAD

**Issue by Ravizz** [azet12/KAD#556]
KONTYNUACJA: https://github.com/azet12/KAD/issues/549

Ponoć jak twierdziłeś miałeś tu wpadać raz na tydzień, to dlaczego tak szybciutko zamknąłeś wątek? Ale pewnie zaraz coś wymyślisz, zaprzeczysz i napiszesz bajeczkę, że akurat wpadłeś przypadkowo, akurat wtedy gdy zacząłeś mocno przegrywać dyskusję, to wpadłeś przypadkowo, następnie przypadkowo nawypisywałeś na mnie bzdur, a potem przypadkowo zamknąłeś wątek bo przypadkowo znalazłeś jakiś powód...żałosne.

Współczuję porażki i tchórzostwa, gdzie uciekasz trollu @azet12? Dyskusja jeszcze nieskończona, nawypisywałeś znowu jakieś bzdury na mnie i szybciutko zablokowałeś wątek nie dając mi się odnieść, (więc moja przepowiednia się spełniła), czy w taki sposób podobnie jak twój kolega @TomekFx prowadzisz dyskusję poprzez zamykanie wątku z braku argumentów? Co będzie następne, ban po cichu tak jak u twojego kolegów trolli @MajkiIT , @TomekFx ? Takie nieuczciwe chwyty poniżej pasa stosujesz gdy zaczynasz przegrywać dyskusję, jak widać tak jak już pisałem wcześniej tylko na pokaz / na pozór nie zamknąłeś dyskusji wcześniej, albo łudziłeś się, że uda ci się mnie strolować, ale ci się nie udało, więc poczekaj chwileczkę, jeszcze nie skończyłem cię niszczyć, jak skończę to zamkniesz sobie wątek:

> @azet12 :
> w 3 różnych miejscach zostałem bezpodstawnie naubliżany i zbanowany
> Ciekawe dlaczego! Czy ty w taki sam sposób rozmawiasz z innymi ludźmi? Nie dostrzegasz, że ty po prostu się o to prosisz?  

W jaki sposób/cytat/dowody proszę a nie nic nieznaczące ogólnikowe pomówienia prymitywny trollu.

> @azet12 : Za wszelką cenę podsycasz ogień... Robisz dziwne, obraźliwe porównania a gniew przewyższa > retorykę. Usilnie wciskasz, jaki to ty jesteś mądry, zupełnie jakbyś miał kompleks. 

W jaki sposób/cytat/dowody proszę a nie nic nieznaczące ogólnikowe pomówienia prymitywny trollu.

> @azet12 : Bezpodstawnie? Chyba żartujesz.

Ty żartujesz , trolując i odwracając kota ogonem, że to ja żartuję, na tym polega trolowanie, na odwracaniu kota ogonem, to ty jesteś tu klaunem, który rozbawia swoimi niczego niedowodzącymi ogólnikami. Tak mocno trolujesz, że aż śmierdzi od ciebie dzikim trollem z jaskini.

> @azet12 :
> @Ravizz : 
> nikt z was nie potrafi podać podstawy/powodu takiego potraktowania mnie
> Może dlatego, że ani ja ani nikt inny nie czyta w myślach adminowi, który dał ci bana?

A do czego ci potrzebne czytanie w myślach admina? Wszystko co napisałem na koncie Ravizz jest publicznie widoczne, czegoś ci tam brakuje?

> @azet12 :
> @Ravizz : Nie na powitanie, hipokryto i trollu
> Wygląda na to, że piszesz tak dużo, że nie za bardzo pamiętasz, co tak naprawdę napisałeś:
>.(Twój pierwszy post pod koniec) Ten wątek pewnie też zostanie szybciutko zamknięty jak tylko wróci @azet12 bo on jest osobnikiem należącym do ich stada, więc zamykaj hieno
> I nawet nie skomentuję twojej logiki, że to niby nie jest obrażanie.

Nie wiem o co ciągle się sadzisz z tą hieną, przecież z tą hieną już 2 razy ci wyjaśniłem, czego jeszcze nie rozumiesz?  Zresztą i tak się nią okazałeś, więc jednak cię nie obrażałem skoro nią jesteś...

> @azet12 :
> @Ravizz : Widzę, że ubliżacie mi i trolujecie dalej
> https://pl.wikipedia.org/wiki/Hipokryzja

Już ci tłumaczyłem, że poza hieną to dalej nazywałem po imieniu, więc czego znowu jeszcze nie rozumiesz i do których moich słów się odnosisz? Poza w jaki sposób/cytat/dowody proszę a nie nic nieznaczące ogólnikowe pomówienia prymitywny trollu, czy jesteś w stanie chociaż raz pokazać jakiś dowód przeciwko mnie i zacytować moje słowa ty prymitywny trollu bez argumentów rzucający nic nie udowadniającyymi ogólnikami oraz odwracający wszystko ogonem?

> @azet12 :
> @Ravizz : nie sądziłem, że podejdziesz do tego tak na sztywno
> 
> https://pl.wikipedia.org/wiki/Ironia

Że niby ty też odnosiłeś się do tych niemców ironiczne? Buahaha, piana ci z pyska ciekła, a teraz wmawia, że tak samo jak ja pisał to ironicznie, co za odwracający kota ogonem z powodu argumentów troll jaskiniowy.

> @azet12 :
> @Ravizz : Dzięki za potwierdzenie, że moja wypowiedź o waszej taktyce i próbach zrobienia zrobienia ze mnie wariata, umieszczona w moim poprzednim poście, jest prawdą
> Nieważne, jak ci odpowiem, to ty i tak nadinterpretujesz moje słowa i znowu piszesz esej, w którym bez przerwy się powtarzasz i czyta się to z niesamowitym znudzeniem.
> Napisałem "my" ze względu na twoje określenia w całą grupę osób, które tworzą filtry - używałeś po prostu tej samej formy... Zagadka rozwiązana! Słyszałeś może o brzytwie Ockhama? Pewnie nie.

Bo z tej całej grupy osób tworzącej filtry wszyscy są przeciwko mnie, pomimo, że nie mają ani jednego argumentu przeciwko mnie i nie potrafią mi nic udowodnić ani zarzucić poza obraźliwymi nic nieudowadniającymi ogólnikowymi pomówieniami lub odwracaniem kota ogonem, jednocześnie nie mają ani jednego argumentu na swoją obronę, obrażano mnie i banowano bez powodu, a wszyscy dookoła to widzieli, a nie reagowali (znieczulica) i na to przyzwalali, a każdy kto się odzywa w tej sprawie atakuje tylko mnie, więc zdecydowanie moje odnoszenie się do was jest logiczne, i jeśli ktoś tu brzmi jak szaleniec, to ten kto twierdzi inaczej (ty) .

> @azet12 : > To, co robisz, to podręcznikowe snucie teorii spiskowych. Szukasz w moich wypowiedziach czegokolwiek, by tylko wmówić sobie bzdury.

To co ty robisz to to co opisane jest pod linkami które wkleiłem, i na pewno też podręcznikowe, twoja choroba psychiczna polegająca na ostrym bardzo bardzo ostrym i skumulowanym trolowaniu oraz laniu hipokryzji całymi wiadrami, oraz odwracaniu kota ogonem, jak stary jaskiniowy troll, jedyne co umiesz to obrzucać obraźliwymi nic nieudowadniającymi ogólnikowymi pomówieniami i odwracać kota ogonem, wszystko to robisz z powodu braku jakiegokolwiek argumentu przeciwko mnie, nic mi nie udowodniłeś i nic nie potrafisz udowodnić, jak wszyscy inni zresztą, a to ja udowodniłem wam wszystko o co was oskarżałem za pomocą czarno-białych bezspornych argumentów. Przegraliście wszyscy dyskusję już od samego początku, leżysz i kwiczysz i bronisz się ostrym trolowaniem i hipokryzją, a to trzeba leczyć jeśli w ogóle nie jest za późno.

> @Ravizz : kontynuujecie bezpodstawną (pozbawioną jakichkolwiek argumentów i podstaw) drugorzędną i personalną agresję w moim kierunku
> Nie będę się tłumaczył za innego admina, a szczególnie tobie, ponieważ twoja agresywna postawa wcale do tego nie zachęca (małe przypomnienie: nic tobie nie zrobiłem).

Jak na razie to ja w dyskusji operuję argumentami, a ty/wy ogólnikowymi pomówieniami, odwracaniem kota ogonem, hipokryzją. Twoja/wasza agresywna postawa zbuntowanego trolla jaskiniowego, który pomimo, że przegrał tę dyskusję już na starcie zanim ją na dobre zaczął, to dalej próbuję na siłę za pomocą ogólnikowych obraźliwych pomówień, odwracania kota ogonem i laniem wiader hipokryzji, wygrać tę przegraną dyskusję, albo chociaż zachować pozory zwycięstwa, żeby inni nie zobaczyli jak leżysz i kwiczysz z powodu braku jakiegokolwiek argumentu na mnie, nie zachęca do dalszej dyskusji z tobą. Nie potrafisz zacytować i odnieść się do żadnych moich konkretnych słów.

> @Ravizz : No jeszcze zapomniałeś buzi dać
> @azet12 : Wybacz, że podziękowałem mu za komplement(?).
>  http://nonsensopedia.wikia.com/wiki/Burak_(osoba)
> Przez twoje wszystkie posty utrzymujesz negatywną atmosferę i nie postanowiłeś przedyskutować tego jak człowiek. Wolałeś się wywyższać. Być może sprawia ci to przyjemność. Przykro mi, ale musisz znaleźć inne osoby do takiej zabawy.
> Potraktuj zamknięcie tego tematu jako mój szacunek wobec twojego czasu, byś znowu nie musiał pisać takich samych rozprawek i zajął się czymś ciekawszym.

Żartujesz sobie, klaunie cyrkowy, znowu śmierdzący jaskiniowy trollu, odwracasz kota ogonem i lejesz wiadrami hipokryzję, podobnie jak robiłeś to w poprzednich swoich komentarzach od samego początku dyskusji, ale w tym komentarzu skondensowana ilość trolowania, rzucania ogólnikami, hipokryzji i odwracania kota ogonem z twojej strony jest tak przeraźliwie ogromna, że jestem zmuszony zaliczyć ciebie do grupy wyjątkowo agresywnych trolli, ale nawet z takimi sobie bez problemu daję radę, poodkręcajmy trollu, wszystkie złośliwe bzdury, które na mnie wypisujesz:

> @azet12 : Przez twoje wszystkie posty utrzymujesz negatywną atmosferę i nie postanowiłeś przedyskutować tego jak człowiek. 

1) znowu żadnych konkretów/szczegółów/cytatów/argumentów, znowu jakieś fantasy ogólnikowe nic nieudowadniające pomówienia
2) jak mogę budować negatywną atmosferę nic nie robiąc złego? Przecież nie za pomocą argumentów, odpada bo za pomocą argumentów, można budować tylko prawdę i prawdziwą atmosferę. Budować negatywną atmosferę można za pomocą takich zachowań jakie ty/wy przedstawiacie, czyli za pomocą bezpodstawnego obrażania/banowania/ogólnikowego pomawiania, trolowania, lania hipokryzji, odwracania kota ogonem, zamykania wątków ze strachu przed porażką na argumenty, takie parszywe zachowania budują negatywną atmosferę, ja tworzę/buduję tylko prawdę i prawdziwą atmosferę opartą na argumentach i faktach, to wy tworzycie negatywny fałsz i obłudę, podwójne standardy, karacie ofiary, bronicie zakolegowanych sprawców i atakujecie mnie, nic mi wcześniej nie udowodniwszy.

> @azet12 :  Wolałeś się wywyższać. Być może sprawia ci to przyjemność. Przykro mi, ale musisz znaleźć inne osoby do takiej zabawy.

Ty podły trollu, nie umiesz nic sam wymyśleć na mnie, nie ściągaj i nie papuguj ode mnie i nie odwracaj znowu kota ogonem, to ja pisałem wcześniej o tym, że jeśli wy chcecie się pobawić w obrażanie i wypisywanie bzdur to sobie poszukajcie kogoś innego.

> @azet12: Potraktuj zamknięcie tego tematu jako mój szacunek wobec twojego czasu, byś znowu nie musiał pisać takich samych rozprawek i zajął się czymś ciekawszym.

Normalnie parsknąłem śmiechem trollu, gdy zobaczyłem twoje zamknięcie i zablokowanie w pośpiechu  i panice przede mną tego wątku ze strachu przed porażką na argumenty ze mną, poprzedzone komentarzem zawierającym na odchodne skumulowaną dawkę jadowitego trolowania, ogólnikowych pomówień, wader hipokryzji i odwracania kota ogonem w moją stronę. Schowałeś głowę w piasek jak struś, widząc nadchodzącą apokalipsę twojego upadku w tej dyskusji, a następnie schwytałeś się brzytwy / ostatniej deski ratunku jak większość adminów z twoim kolegą Tomeczkiem na czele, czyli użyłeś przycisku zamknij/zablokuj przeznaczonego dla tchórzy, którzy przegrywają w dyskusji. Gratuluję odwagi i współczuję porażki ! Miło widzieć jak wróg przyznaje się do porażki wypisując przed zamknięciem wątku brednie w moją stronę, a potem go zamykając żebym tylko ich nie poodkręcał bo co sobie pomyślą czytelnicy gdy zobaczą takiego nieudacznika/trolla jak @azet12 przegrywającego dyskusję? Wiedziałem, trollu że zamkniesz i zablokujesz ten wątek ze strachu, dlatego na początku już nawet napisałem przepowiednię, której spełnienie było tylko kwestią czasu:

> @Ravizz: Ten wątek pewnie też zostanie szybciutko zamknięty jak tylko wróci @azet12 bo on jest osobnikiem należącym do ich stada, więc zamykaj hieno, a w razie gdybyś przed zamknięciem nawypisywał na mnie bzdur, to będą to tylko bzdury, bo wy mi nic nie udowodniliście i nie potraficie udowodnić, a tylko umiecie ubliżać i wymyślać, pisz sobie co chcesz i tak będzie to jeden wielki fałsz. Jeśli coś na mnie nabazgrzesz, to spodziewam się, że spróbujesz zasugerować ludziom, że w tym komentarzu zwyzywałem, ale już pisałem, że nie zwyzywałem, tylko nazywam, a to różnica, nazywam was po imieniu

> @Ravizz: Już wiem dlaczego ten wątek nie został zamknięty od razu, z braku realnych argumentów przeciwko mnie (nie jesteście mi w stanie nic udowodnić i jednocześnie uzasadnić waszego chamskiego zachowania wobec mnie) wasz plan polega na tym, żeby rzucić się na mnie w kilku na jednego, jak hieny na osaczoną impalę, sprowokować mnie i naobrażać, i jeszcze bezczelnie wmówić, że to moja wina, że jestem przez was zagryzany, rozdmuchać wszystko i zrobić nagonkę, zanim wątek zostanie zamknięty, bo jeśli by tak zamknąć wątek od razu bez odpisywania mi, to oznaczałoby to wasze przyznanie się do winy, bo jak to mówi przysłowie: "nieobecni nie mają racji" czyli kto nie bierze udziału w dyskusji ten nie ma racji, więc byle coś na mnie powypisywać, najlepiej poobrażać powyśmiewać, a potem chamsko zablokować wątek nie dając mi możliwości odpisania, obrony i celnego zripostowania wam (ośmieszenia was). 

Nic dodać nic ująć, być może nie zamknąłeś od razu wątku bo chciałeś na przekór pokazać (fałszywie), że taki nie jesteś, albo łudziłeś się, że mnie pokonasz w dyskusji za pomocą trolowania, ale niestety nie udało ci się więc hop i szybciutko wątek zablokowany, cóż żałosne to, stek bzdur w moją stronę i szybkie zablokowanie, i jak ja mam przed tym się obronić?

Gratuluję odwagi i współczuję porażki i tchórzostwa ty jaskiniowy wyjątkowo agresywnie trollujący osobniku.

https://pl.wikipedia.org/wiki/Trollowanie
https://pl.wikipedia.org/wiki/Erystyka
https://pl.wikipedia.org/wiki/Hejter
http://educover.pl/czasopismo/trolle-hejterzy-czyli-prawdziwe-utrapienie-internetowej-spolecznosci/
http://kontrowersyjnapanidomu.blog.pl/2014/07/23/znieczulica-choroba-zakazna-charakteryzujaca-sie/

Agresywny trollu @azet12, widząc cię zniszczonego w dyskusji na realne argumenty, i po twoich ciosach poniżej pasa / chwytaniu się brzytwy / ostatniej deski ratunku / schowania głowy w piasek czyli zablokowaniu poprzedniego wątku po uprzednim "dołożeniu mi" tak żebym nie mógł odpisać i się obronić przed wypisywanymi przez ciebie bzdurami, spodziewam się (a moje przypuszczenia jak widać się sprawdzają), że powtórzysz swoje plugawe i tchórzliwe zachowanie i tym razem ostatnim twoim tchnieniem, które z siebie wydusić będzie kolejny żałosny stek bzdur w moją stronę + ban, tak żebym znowu nie mógł odpisać i obalić wypisywanych przez ciebie bzdur, w ten sposób z powodu braku argumentów słownych, sięgasz po przysłowiową pałkę czyli po argumenty siłowe. Żal mi ciebie, że nie stać się na nic więcej, na prawdziwą męską dyskusję, że nie potrafisz nic udowodnić, albo przyznać się do porażki. przyznać komuś rację, a tylko trolować, lać wiadrami hipokryzję, odwracać kota ogonem i obrzucać ogólnikami,  a następnie blokować wątki i najprawdopodobniej zaraz mi także dasz bana.  

Więc chcę jedynie uprzedzić czytelników, że ten prosty jaskiniowy troll zanim mi założy bezpodstawnego bana (no chyba, że znowu na pozór będzie chciał pokazać, że on nie z tych) to najprawdopodobniej sformułuje swoją ostatnią wypowiedź w tak zmanipulowany sposób, żeby ten ban był pozornie uzasadniony, nawypisuje na mnie kolejny stek bzdur, ogólnikowych pomówień, wyleje wiadra hipokryzji, poodwraca kota ogonem, żeby nabrać czytelników, że to ja tu jestem czemuś winny i przedstawić mnie w jak najgorszym świetle, a siebie jako nieskazitelnego i niewinnego, bo byłoby dla niego zapewne tragedią życiową, gdyby czytelnicy zobaczyli jak przegrał dyskusję i że jest agresywnym trollem, co jest już faktem, więc mam nadzieje, że na obecnym etapie dyskusji nie uda się jemu już nic plugawego i fałszywego na mnie wymyśleć przed banem. Gdyby jednak coś tam złośliwego cwanie nawypisywał to będą to tylko jego śmierdzące pierdy z nieumytego dupska, bo cokolowiek on na mnie nawypisuje to ja się z łatwością bronię, ale niestety nie mogę się bronić jeśli taka pierdolona żałosna kurwa mi da bana, więc od razu uprzedzam czytelników, nie wierzcie w te scieki, które na mnie nawypisuje ten parszywy śmierdzący troll jaskiniowy, który nic mi nie udowodnił i nie udowodni. Koleś po prostu odleciał do krainy trolli jaskiniowców jak zresztą cała ta zgraja pojebów od filtrów.

Na koniec trollu spójrz w lustro i zobacz siebie:
https://supportbreakfast.files.wordpress.com/2017/04/internet-troll-650.jpg

**Comment by azet12** [comment]
Dyskusja jest jak najbardziej skończona. Przestań mnie nękać. Jeszcze jeden taki temat i dostajesz bana za zaśmiecanie mojego repo i wyzywaniu każdego po drodze.
