### ISSUE TITLE
Blogspot - strony offline

### ISSUE THREAD

**Issue by xMaap** [azet12/KAD#573]
zmienkolorfejsazafree.blogspot.com
zmien-koolor.blogspot.com
zachomikowane.blogspot.com
staw-tlo.blogspot.com
testowanietwojegoiq.blogspot.com
szybki-przeglad.blogspot.com
szokinfor24.blogspot.com
szokinfo247.blogspot.com
suczki-mlode.blogspot.com
sspawdzktopodgglada.blogspot.com
sprawdzktopodgglada.blogspot.com
snapchat-save.blogspot.com
sexfabryki.blogspot.com
sexfabryka*.blogspot.com
sex-fabryka*.blogspot.com
pryszcz-wideo.blogspot.com
pokemon2k16go.blogspot.com
pokemon-go-pakiety.blogspot.com
okaleczona15-llatka.blogspot.com
okaleczon15-lattka.blogspot.com
natkaaa1998.blogspot.com
mojekumpele.blogspot.com
koloryfejsa.blogspot.com
kolloryfejsa.blogspot.com
kollory-fejsa.blogspot.com
infoszook24.blogspot.com
informacjeszok24.blogspot.com
generatorfreegames.blogspot.com
friendslistfbb.blogspot.com
fbviewerv75.blogspot.com
faceviewe.blogspot.com
euro2016-doladowanie.blogspot.com
euro-doladowania.blogspot.com
e-bony-1500zl.blogspot.com
doladuj-tutaj.blogspot.com
doladowanie50pln.blogspot.com
doladowania50pln.blogspot.com
datasmierci01.blogspot.com
dataasmierci.blogspot.com
bony-na-dzienkobiet2017.blogspot.com
bon1500.blogspot.com
bon-na-dzienkobiet2017.blogspot.com
blyskawiczne-doladowania.blogspot.com
aktualizacjafacebooka.blogspot.com
5facebookfrienddel.blogspot.com
1kolorrfaceb.blogspot.com

**Comment by azet12** [comment]
Niektóre strony nie zostały usunięte ze względu na możliwość powrotu ich działania.
