### ISSUE TITLE
www.penera.pl 

### ISSUE THREAD

**Issue by takenek** [azet12/KAD#594]
Cześć,
Czy na pewno strona www.penera.pl powinna zostać umieszczona na liście?
Właśnie zauważyłem, że na https://www.idioci.pl/ nie działają mi filmiki, po diagnozie okazało się, że filmy są umieszczane właśnie w serwisie www.penera.pl i Twój filtr blokuje odtwarzanie filmów:

21:22:37 |   | \|\|www.penera.pl^ | -- | media | http://www.penera.pl/upload/upload_video/c6793560af87583ea00f31cc25037508.mp4 -- | -- | -- | -- | -- | --

Pozdr
TaKeN

**Comment by azet12** [comment]
Cześć.

Strona ta najprawdopodobniej została dodana ze względu na to, że posiadała możliwość zarejestrowania/zalogowania poprzez aplikację facebookową, która spamowała na tablicy bez zgody.
Ewentualnie ze względu na dużą ilość reklam.

Właśnie sprawdziłem i wygląda na to, że aplikacja już nie działa.
Usunąłem stronę z listy, jednak zawsze może do niej wrócić, jeśli będzie dokonywała podejrzanych akcji.
