### ISSUE TITLE
fake sklep 

### ISSUE THREAD

**Issue by MajkiIT** [azet12/KAD#664]
https://zaufanatrzeciastrona.pl/post/uwaga-na-falszywy-sklep-pole-henny-oszusci-modyfikuja-swoj-schemat-ataku/

**Comment by azet12** [comment]
już offline

**Comment by MajkiIT** [comment]
no jak offline https://pole-henny.com/index.php

**Comment by azet12** [comment]
@MajkiIT Rzeczywiście, przeoczyłem tę stronę.
