### ISSUE TITLE
adblock plus nie wspiera pełnego blokowania stron

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/KAD#670]
![2018-07-21-kad_kad txt at master azet12_kad](https://user-images.githubusercontent.com/5884000/43035176-1cc6be60-8ceb-11e8-8910-550e8084c51a.png)

proszę usuń przedrostek `[Adblock Plus 2.0]` z początku listy
https://github.com/azet12/KAD/blob/master/KAD.txt

**Comment by azet12** [comment]
Filtr nie powstał dla Adblocka, jednak bez tego dodatku filtr nie będzie w ogóle działał na nim działał, więc na chwilę obecną zostawiam to.
Dodam jednak informację w https://github.com/azet12/KAD/issues/671
