### ISSUE TITLE
proszę dodaj informacje o wymaganiu ublocka origin do poprawnego działania listy

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/KAD#671]
![2018-07-21-kad_kad txt at master azet12_kad](https://user-images.githubusercontent.com/5884000/43035187-4f052ad8-8ceb-11e8-891f-b9c608a5a81f.png)
https://github.com/azet12/KAD/blob/master/KAD.txt

**Comment by azet12** [comment]
Tak zrobię
