### ISSUE TITLE
login.microsoftdrive.one/owa/login/?authkey=

### ISSUE THREAD

**Issue by xMaap** [azet12/KAD#725]

**Comment by azet12** [comment]
Nie działa już.
Strony phishing zgłaszaj też zawsze tutaj:
https://toolbar.netcraft.com/report_url
https://safebrowsing.google.com/safebrowsing/report_phish/?hl=pl

**Comment by xMaap** [comment]
Jak nie działa?
![opera zdjecie_2018-08-24_005607_login microsoftdrive one](https://user-images.githubusercontent.com/36385327/44556126-879caf80-a738-11e8-9774-d313f47e0469.png)

**Comment by azet12** [comment]
Odśwież kilka razy, bo strona pobiera ci się z pamięci podręcznej a nie z sieci.

https://isitup.org/login.microsoftdrive.one
