### ISSUE TITLE
Getin Holding

### ISSUE THREAD

**Issue by xMaap** [azet12/KAD#756]
https://getin.pl
https://www.ideabank.pl
https://taxcare.pl
http://www.mwtrade.pl
https://www.idealeasing.pl
https://www.carcade.com
https://www.ideabank.ua
https://www.ideabank.by
https://ro.idea-bank.ro

https://www.bankier.pl/wiadomosc/Getin-Holding-zagrozony-wpisem-na-liste-alertow-7612892.html
https://www.rp.pl/Kraj/309109897-Podkomisja-zbada-afere-GetBack.html
https://businessinsider.com.pl/finanse/getback-historia-afery-o-ryzyku-pisalismy-juz-rok-temu/gvqbnhthttps://www.tvn24.pl/wiadomosci-z-kraju,3/mechanizm-getback-afera-wieksza-niz-amber-gold,867520.html

**Comment by azet12** [comment]
Blokowanie stron całego banku do którego ludzie się logują mija się z celem.
