### ISSUE TITLE
sukces.pl

### ISSUE THREAD

**Issue by xMaap** [azet12/KAD#781]
http://sukces.pl
http://www.mistrzmotywacji.pl

**Comment by MajkiIT** [comment]
Ale to normalne
https://www.youtube.com/watch?v=ys6bPuw69OQ

**Comment by azet12** [comment]
Znalazłem strony bardzo podobne do tego, więc dodam do podejrzanych.

[NSFW] 
```
http://oswieconykochanek.pl
http://www.pozycjeseksualne.pl/
http://sug.com.pl/1/koszyk
```
