### ISSUE TITLE
wiesci24.pl

### ISSUE THREAD

**Issue by annaparker** [azet12/KAD#795]
Witam, dlaczego wiesci24.pl są blokowane? Na wykopie jest na głównej link, klikam i... zablokowano. Patrzę, a to KAD. ;) Myślę, że nie tędy droga, żeby cenzurować Internet. Sugeruję wyrzucenie tej strony z listy zakazanych stron.

**Comment by azet12** [comment]
Masz rację. Usuwam.

**Comment by xMaap** [comment]
@azet12 https://github.com/azet12/KAD/issues/649#issuecomment-405580081

**Comment by azet12** [comment]
@xMaap widziałem, jednak wolę unikać kwestii politycznych poprzez blokowanie tego typu stron. Dlatego na filtrze nie znajduje się fronda na przykład, mimo że osobiście nie cierpię tej strony.
