### ISSUE TITLE
prezi.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/KAD#808]
`https://prezi.com/7eatqy4ofpwm/ken-follett-wejsc-miedzy-lwy-audiobook-pl-mp364-download-free/`

`http://trustedirectdownload.com/?name=Ken_Follett__Wej%C5%9B%C4%87_mi%C4%99dzy_lwy_Audiobook_PL_mp364`

scam

**Comment by krystian3w** [comment]
Całego prezi nie blokujmy.

**Comment by azet12** [comment]
Indywidualne przypadki spamu na platformie gdzie każdy może coś dodać można zgłaszać do administracji. Oczywiście całego prezi nie blokuję.

`http://trustedirectdownload.com`
`https://zeezi4ei.com/`
`bestbook-library.com`
