### ISSUE TITLE
dascoinexplorer.com

### ISSUE THREAD

**Issue by xMaap** [azet12/KAD#829]
https://dascoinexplorer.com
https://excelz.com
https://bo.nasdacoin.io
https://nasdacoin.io
http://nasdapool.com
http://nasdacoin.info

**Comment by azet12** [comment]
Na tych stronach nie widzę nic bezpośrednio groźnego.

**Comment by xMaap** [comment]
@azet12 poczekaj o FutureNet, FutureAdPro, DasCoin, Netleaders to jest zwykłe oszustwo.

https://www.fxmag.pl/artykul/dascoin-oficjalnie-uznany-za-scam-przez-amerykanskiego-regulatora
https://kryptowaluty.expert/czy-to-koniec-futurenet-i-futureadpro-goraca-dyskusja/
https://kryptowaluty.expert/na-wniosek-tradingjam-prokuratura-wszczela-postepowanie-w-sprawie-dascoin/
https://businessinsider.com.pl/finanse/kryptowaluty/dascoin-liderzy-o-przesluchaniach-przez-cbs-i-prokurature/ep3hhg3
https://pomorska.pl/dascoin-to-piramida-finansowa-sad-i-uokik-ocenia/ar/13713550

**Comment by azet12** [comment]
@xMaap Ok, ale nie będę blokował stron z historiami transakcji, bo same w sobie nie są groźne.
Dodam
`||excelz.com^ ,
||nasdacoin.io^`
