### ISSUE TITLE
zalogowany.nd.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#83]
Odbierz doładowanie 25PLN
Z okazji istnienia naszej strony od 25 miesięcy rozdajemy doładowania do każdej sieci w kwocie 25zł.
Podaj swój numer telefonu
Potwierdzam
* pole wymagane Promocyjna aktywacja 0 zł. Przyjmuję do wiadomości, iż zamawiam treści cyfrowe nie zapisane na nośniku materialnym i wyrażam zgodę na rozpoczęcie spełniania świadczenia przed upływem terminu do odstąpienia od umowy oraz potwierdzam, że jestem świadomy utraty prawa odstąpienia od umowy z chwilą rozpoczęcia spełniania świadczenia. Akceptuję regulamin i wyrażam zgodę na rozpoczęcie świadczenia usługi przed upływem terminu na odstąpienie od umowy (14 dni). Wiem, że tracę ustawowe prawo do odstąpienia, ale mogę w każdej chwili wypowiedzieć umowę. Rozumiem, że zamówienie usługi wiąże się z obowiązkiem zapłaty.

**Comment by azet12** [comment]
także zalogowany.pl
