### ISSUE TITLE
81 serwisów pożyczkowych przed którymi przestrzega UOKiK

### ISSUE THREAD

**Issue by blocker999** [azet12/KAD#836]
https://www.zadluzenia.com/geldor-artur-karwot-ostrzezenie-uokik/

**Comment by xMaap** [comment]
3000-od-reki.pl

punkt-pozyczka.pl

geldorbank.pl

alfapro.pl

rozsadnapozyczka.pl

gotowka.in

alisto-pozyczki.pl

rzetelna-pozyczka.pl

gotowka.online

as-chwilowka.pl

stopkomornikowi.pl

indygo.top

besavia.pl

super-tania-chwilowka.pl

kasaani.pl

bezbiku.pro

superportfel.eu

korzystapozyczka.pl

cedino.pl

szczesliwagotowka.pl

kredyt.li

eskolon.pl

szybka-wyplata.pl

kredytomat.pro

euresco.pl

szybkapozyczkabezbik.eu

mamkase.pl

eurcontex.eu

tysiaczek.pl

mega-chwilowka.pl

fevitum.pl

vipon.pl

nectus.pl

fresh-finance.pl

viskon.pl

pieniadzedlapotrzebujacych.pl

gotowkanadowod.pl

w15min.com

pomoc-finansowa.info

gotowkanadzis.pl

wraplo.pl

postania.pl

green-kredyt.pl

wybierzpieniadze.pl

pożyczaj.online.pl

grumman.pl

zebrapozyczki.pl

pozyczajbezstresu.pl

kirchbaum.pl

12kredyt.pl

pozyczka-sms.pl

korphan.pl

w1godz.pl

pozyczkabezbik-u.pl

kredyt-na-pesel.pl

bank-not.pl

pozyczki-bez-bik.top

lopon.pl

credit-in.pl

pozyczkiprywatne.com

onerque-kredyt.pl

credit-union.pl

sa-exclusive.pl

oplacalna-gotowka.pl

delan.pl

splac-zaleglosci.pl

pomocnapozyczka.pro

dinarion.pl

t-kredyt.com

pozyczka-tanio-szybko.pl

do50000.pl

tgw-gotowka.pl

pozyczka.click

dyv.pl

uwaga-pozyczka.pl

pozyczkahit.pl

e-thyssen.pl

windwood.pl

pozyczkanatelefon24.pl

gdb-finance.pl

wyplac-dzisiaj.pl
