### ISSUE TITLE
dofinansowanie-lubelskie.pl

### ISSUE THREAD

**Issue by xMaap** [azet12/KAD#842]
dofinansowanie-lubelskie.pl
dofinansowanie-lodzkie.pl
dofinansowanie-podlaskie.pl
dofinansowanie-wielkopolskie.pl
dofinansowanie-slaskie.pl
dofinansowanie-dolnoslaskie.pl
dofinansowanie-kujawsko-pomorskie.pl
https://i-store365.com/pl/fusion_fuelsaver/2/index.html?gclid=Cj0KCQjw2f7bBRDVARIsAAwYBBvQshfrqqC8qWSyJlkaA5mMNoBQDZbwXwi9BV0zI2Ljociyx1VECxoaAiHDEALw_wcB#footer
https://obos-ankiety.pl

https://niebezpiecznik.pl/post/sprzedawca-kursow-jezykowych-z-dotacjami-straszy-sadem-za-nieodebranie-paczki-rekomendujemy-zignorowanie-grozb-i-nieodbieranie-paczek/
https://niebezpiecznik.pl/post/uwazaj-na-kursy-jezykowe-z-dotacjami-nie-wiadomo-kto-przetwarza-dane-osobowe-ale-mozna-sie-tego-domyslic/

**Comment by hawkeye116477** [comment]
To już było dodane, ale najwyraźniej zostało usunięte.

**Comment by azet12** [comment]
@hawkeye116477 Cześć, nie zauważyłem twojego maila z grudnia. Wysłałem ci zaproszenie do edycji, możesz aktualizować jak chcesz. Na chwilę obecną nie chcę wszystkiego przenosić na PolishFilters, mam nadzieję, że ci to nie przeszkadza.

**Comment by hawkeye116477** [comment]
Wysłałem odpowiedź na maila jak coś.
