### ISSUE TITLE
kontakt.esite.pl

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#86]
Serwis jest usługą subskrypcyjną dostępną w sieci Plus, T-Mobile, Orange, Play. Dla sieci PLUS poprzez wysłanie sms aktywacyjnego wpisanie na stronie kodu PIN otrzymanego darmowym sms'em na podany numer telefonu komórkowego użytkownik potwierdza zaakceptowanie Regulaminu serwisu. Wraz z aktywacją subskrypcji użytkownik otrzymuje wynik wykonanego testu. Subskrybenci serwisu otrzymują sms w poniedziałek, środę i piątek około godziny 10:00. Sms zawiera informacje od usłudze. Koszt za każdy sms przychodzący to 6,15zł z VAT. Dezaktywacji subskrypcji można dokonać w dowolnym momencie poprzez wysłanie SMS o treści STOP free pod numer 60596
(Koszt wysłania sms to 0 zł). W przypadku reklamacji prosimy wysłać email poprzez formularz kontaktowy na stronie.
Życzymy przyjemnego korzystania ze strony!

**Comment by azet12** [comment]
także zalogowany.pl
