### ISSUE TITLE
pl.info-fitness.com

### ISSUE THREAD

**Issue by xxcriticxx** [azet12/KAD#94]
http://pl.info-fitness.com/wap_wagaInf/index.php

Serwis INF jest usługą subskrypcyjną umożliwiającą dostęp do kontentu na telefon komórkowy. Szczegółowe warunki korzystania z serwisu określa regulamin. Serwis dostępny w sieciach: Orange, Plus, T-Mobile i Play. Koszt subskrypcji serwisu INF wynosi 3,69 zł brutto, za każdy otrzymany przez użytkownika SMS z linkiem do portalu. Tygodniowo otrzymasz max. 7 SMSów/tydzień do czasu rezygnacji z usługi, której można dokonać wysyłając SMS o treści STOP INF na numer 60320. Obowiązują standardowe opłaty za usługę WAP, GPRS i UMTS naliczane zgodnie z taryfą danego operatora sieci komórkowej. Min. wiek uczestnika to 18 lat. Użytkownik aktywując usługę potwierdza przeczytanie, zrozumienie i wyrażenie zgody na obowiązujące zapisy regulaminu. Dostawcą usługi jest Data Premium de Venezuela 11, C.A. Los Palos Grandes, Caracas 1060, Venezuela; RIF: J-31743513-3, info.pl@datapremium.net. Podmiotem realizującym dodatkowe świadczenie jest: NVIA Gestión de Datos, S.L. Infolinia: 48586982010, Regulamin

**Comment by azet12** [comment]
już było na filtrze ale źle blokowało
`www.info-fitness.com` na `info-fitness.com` (naprawione)
